// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ApiKeyCreate
 */
export type ApiKeyCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Scopes
     */
    scopes?: Array<string>;
    /**
     * Expires In Days
     */
    expires_in_days?: number | null;
};

/**
 * ApiKeyCreated
 */
export type ApiKeyCreated = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Scopes
     */
    scopes: Array<string>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Last Used At
     */
    last_used_at: string | null;
    /**
     * Token
     *
     * Shown once. It cannot be retrieved again.
     */
    token: string;
};

/**
 * ApiKeyResponse
 */
export type ApiKeyResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Scopes
     */
    scopes: Array<string>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Last Used At
     */
    last_used_at: string | null;
};

/**
 * AssignRequest
 */
export type AssignRequest = {
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Amount
     */
    amount: number | string;
};

/**
 * AuthConfig
 */
export type AuthConfig = {
    /**
     * Login Url
     */
    login_url: string;
};

/**
 * Balance
 */
export type Balance = {
    /**
     * Person
     */
    person: string;
    /**
     * Net
     */
    net: string;
};

/**
 * BalanceSheet
 */
export type BalanceSheet = {
    /**
     * Currency
     */
    currency: string;
    /**
     * Balances
     */
    balances: Array<Balance>;
    /**
     * Settle Up
     */
    settle_up: Array<Settlement>;
};

/**
 * Bucket
 */
export type BucketInput = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Group
     */
    group?: string | null;
    target?: TargetInput | null;
    /**
     * Archived
     */
    archived?: boolean;
};

/**
 * Bucket
 */
export type BucketOutput = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Group
     */
    group?: string | null;
    target?: TargetOutput | null;
    /**
     * Archived
     */
    archived?: boolean;
};

/**
 * BucketState
 */
export type BucketState = {
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Name
     */
    name: string;
    /**
     * Group
     */
    group: string | null;
    /**
     * Assigned
     */
    assigned: string;
    /**
     * Activity
     */
    activity: string;
    /**
     * Available
     */
    available: string;
    /**
     * Target
     */
    target: string | null;
};

/**
 * BudgetConnect
 */
export type BudgetConnect = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Repo
     *
     * owner/repo on GitHub
     */
    repo: string;
};

/**
 * BudgetSummary
 */
export type BudgetSummary = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Repo
     */
    repo: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Branch
     */
    branch: string;
    /**
     * Members
     */
    members: Array<Member>;
    /**
     * Me
     *
     * Which member the caller is, if any
     */
    me: string | null;
    /**
     * Can Write
     */
    can_write: boolean;
};

/**
 * CommitRef
 */
export type CommitRef = {
    /**
     * Sha
     */
    sha: string;
    /**
     * Subject
     */
    subject: string;
    /**
     * Author Name
     */
    author_name: string;
    /**
     * Date
     */
    date: string;
};

/**
 * DevicePoll
 */
export type DevicePoll = {
    /**
     * Device Code
     */
    device_code: string;
    /**
     * Name
     */
    name?: string;
};

/**
 * DeviceResult
 */
export type DeviceResult = {
    /**
     * Status
     */
    status: string;
    /**
     * Token
     */
    token?: string | null;
    /**
     * Login
     */
    login?: string | null;
};

/**
 * DeviceStart
 */
export type DeviceStart = {
    /**
     * Device Code
     */
    device_code: string;
    /**
     * User Code
     */
    user_code: string;
    /**
     * Verification Uri
     */
    verification_uri: string;
    /**
     * Interval
     */
    interval: number;
};

/**
 * Entry
 */
export type Entry = {
    /**
     * Id
     */
    id: string;
    kind?: EntryKind;
    /**
     * Date
     */
    date: string;
    /**
     * Payee
     */
    payee: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Paid By
     */
    paid_by: {
        [key: string]: unknown | string;
    };
    /**
     * Shares
     */
    shares: Array<Share>;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Rule
     */
    rule?: string | null;
};

/**
 * EntryCreate
 */
export type EntryCreate = {
    /**
     * Amount
     *
     * Negative for money out, positive for money in
     */
    amount: number | string;
    /**
     * Payee
     */
    payee: string;
    /**
     * Date
     *
     * Defaults to today
     */
    date?: string | null;
    kind?: EntryKind;
    /**
     * Currency
     *
     * Defaults to the budget currency
     */
    currency?: string | null;
    /**
     * Paid By
     *
     * Defaults to the whole amount from the calling user
     */
    paid_by?: {
        [key: string]: number | string;
    } | null;
    /**
     * Shares
     *
     * Explicit split. When omitted, rules decide.
     */
    shares?: Array<ShareInputInput> | null;
    /**
     * Bucket
     *
     * Book every share against this bucket, overriding the rule
     */
    bucket?: string | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
};

/**
 * EntryKind
 */
export type EntryKind = 'expense' | 'income' | 'transfer' | 'settlement';

/**
 * EntryList
 */
export type EntryList = {
    /**
     * Entries
     */
    entries: Array<Entry>;
    /**
     * Total
     */
    total: number;
};

/**
 * EntryResponse
 */
export type EntryResponse = {
    entry: Entry;
    /**
     * Commit
     *
     * Sha of the commit that recorded this change
     */
    commit: string;
};

/**
 * EntryUpdate
 */
export type EntryUpdate = {
    /**
     * Amount
     */
    amount?: number | string | null;
    /**
     * Payee
     */
    payee?: string | null;
    /**
     * Date
     */
    date?: string | null;
    /**
     * Paid By
     */
    paid_by?: {
        [key: string]: number | string;
    } | null;
    /**
     * Shares
     */
    shares?: Array<ShareInputInput> | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HistoryList
 */
export type HistoryList = {
    /**
     * Commits
     */
    commits: Array<CommitRef>;
};

/**
 * Match
 *
 * An empty match matches everything, which is how a catch-all default is written.
 */
export type MatchInput = {
    /**
     * Payee Contains
     */
    payee_contains?: string | null;
    /**
     * Tag
     */
    tag?: string | null;
    /**
     * Paid By
     */
    paid_by?: string | null;
    /**
     * Min Amount
     */
    min_amount?: number | string | null;
};

/**
 * Match
 *
 * An empty match matches everything, which is how a catch-all default is written.
 */
export type MatchOutput = {
    /**
     * Payee Contains
     */
    payee_contains?: string | null;
    /**
     * Tag
     */
    tag?: string | null;
    /**
     * Paid By
     */
    paid_by?: string | null;
    /**
     * Min Amount
     */
    min_amount?: string | null;
};

/**
 * Member
 */
export type Member = {
    /**
     * Person
     */
    person: string;
    /**
     * Name
     */
    name: string;
    /**
     * Github
     */
    github?: string | null;
};

/**
 * MonthResponse
 */
export type MonthResponse = {
    /**
     * Person
     */
    person: string;
    /**
     * Month
     */
    month: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Ready To Assign
     */
    ready_to_assign: string;
    /**
     * Income
     */
    income: string;
    /**
     * Assigned
     */
    assigned: string;
    /**
     * Buckets
     */
    buckets: Array<BucketState>;
};

/**
 * Rule
 */
export type RuleInput = {
    /**
     * Id
     */
    id: string;
    when?: MatchInput;
    /**
     * Split
     */
    split: {
        [key: string]: unknown | number | string;
    };
    /**
     * Bucket
     */
    bucket?: {
        [key: string]: unknown | string;
    };
};

/**
 * Rule
 */
export type RuleOutput = {
    /**
     * Id
     */
    id: string;
    when?: MatchOutput;
    /**
     * Split
     */
    split: {
        [key: string]: unknown | string;
    };
    /**
     * Bucket
     */
    bucket?: {
        [key: string]: unknown | string;
    };
};

/**
 * SettleRequest
 */
export type SettleRequest = {
    /**
     * To
     *
     * Person id being paid
     */
    to: string;
    /**
     * Amount
     */
    amount: number | string;
    /**
     * Date
     */
    date?: string | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * Settlement
 *
 * One suggested payment that reduces outstanding debt.
 */
export type Settlement = {
    /**
     * Payer
     */
    payer: string;
    /**
     * Payee
     */
    payee: string;
    /**
     * Amount
     */
    amount: string;
};

/**
 * Share
 *
 * One person's slice of an entry, booked against one of *their* buckets.
 *
 * A person may hold several shares in one entry when they split their own slice across
 * buckets, so this is not keyed by person.
 */
export type Share = {
    /**
     * Person
     */
    person: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Bucket
     */
    bucket?: string | null;
};

/**
 * ShareInput
 */
export type ShareInputInput = {
    /**
     * Person
     */
    person: string;
    /**
     * Amount
     */
    amount: number | string;
    /**
     * Bucket
     */
    bucket?: string | null;
};

/**
 * ShareInput
 */
export type ShareInputOutput = {
    /**
     * Person
     */
    person: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Bucket
     */
    bucket?: string | null;
};

/**
 * SplitPreview
 */
export type SplitPreview = {
    /**
     * Rule
     */
    rule: string | null;
    /**
     * Shares
     */
    shares: Array<ShareInputOutput>;
};

/**
 * Target
 */
export type TargetInput = {
    /**
     * Kind
     */
    kind: string;
    /**
     * Amount
     */
    amount?: number | string | null;
    /**
     * Due
     */
    due?: string | null;
};

/**
 * Target
 */
export type TargetOutput = {
    /**
     * Kind
     */
    kind: string;
    /**
     * Amount
     */
    amount?: string | null;
    /**
     * Due
     */
    due?: string | null;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Login
     */
    login: string;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetAuthConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/config';
};

export type GetAuthConfigResponses = {
    /**
     * Successful Response
     */
    200: AuthConfig;
};

export type GetAuthConfigResponse = GetAuthConfigResponses[keyof GetAuthConfigResponses];

export type StartGithubLoginData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return Host
         */
        return_host?: string | null;
    };
    url: '/api/v1/auth/github/start';
};

export type StartGithubLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartGithubLoginError = StartGithubLoginErrors[keyof StartGithubLoginErrors];

export type StartGithubLoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FinishGithubLoginData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
        /**
         * State
         */
        state: string;
    };
    url: '/api/v1/auth/github/callback';
};

export type FinishGithubLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FinishGithubLoginError = FinishGithubLoginErrors[keyof FinishGithubLoginErrors];

export type FinishGithubLoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AcceptHandoffData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Ticket
         */
        ticket: string;
    };
    url: '/api/v1/auth/handoff';
};

export type AcceptHandoffErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AcceptHandoffError = AcceptHandoffErrors[keyof AcceptHandoffErrors];

export type AcceptHandoffResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type StartDeviceLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/device/start';
};

export type StartDeviceLoginResponses = {
    /**
     * Successful Response
     */
    200: DeviceStart;
};

export type StartDeviceLoginResponse = StartDeviceLoginResponses[keyof StartDeviceLoginResponses];

export type PollDeviceLoginData = {
    body: DevicePoll;
    path?: never;
    query?: never;
    url: '/api/v1/auth/device/poll';
};

export type PollDeviceLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PollDeviceLoginError = PollDeviceLoginErrors[keyof PollDeviceLoginErrors];

export type PollDeviceLoginResponses = {
    /**
     * Successful Response
     */
    200: DeviceResult;
};

export type PollDeviceLoginResponse = PollDeviceLoginResponses[keyof PollDeviceLoginResponses];

export type ListBudgetsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/budgets';
};

export type ListBudgetsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBudgetsError = ListBudgetsErrors[keyof ListBudgetsErrors];

export type ListBudgetsResponses = {
    /**
     * Response Listbudgets
     *
     * Successful Response
     */
    200: Array<BudgetSummary>;
};

export type ListBudgetsResponse = ListBudgetsResponses[keyof ListBudgetsResponses];

export type ConnectBudgetData = {
    body: BudgetConnect;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/budgets';
};

export type ConnectBudgetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConnectBudgetError = ConnectBudgetErrors[keyof ConnectBudgetErrors];

export type ConnectBudgetResponses = {
    /**
     * Successful Response
     */
    201: BudgetSummary;
};

export type ConnectBudgetResponse = ConnectBudgetResponses[keyof ConnectBudgetResponses];

export type GetBudgetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}';
};

export type GetBudgetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBudgetError = GetBudgetErrors[keyof GetBudgetErrors];

export type GetBudgetResponses = {
    /**
     * Successful Response
     */
    200: BudgetSummary;
};

export type GetBudgetResponse = GetBudgetResponses[keyof GetBudgetResponses];

export type GetMonthData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Month
         */
        month: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: {
        /**
         * Person
         */
        person?: string | null;
    };
    url: '/api/v1/budgets/{budget}/months/{month}';
};

export type GetMonthErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonthError = GetMonthErrors[keyof GetMonthErrors];

export type GetMonthResponses = {
    /**
     * Successful Response
     */
    200: MonthResponse;
};

export type GetMonthResponse = GetMonthResponses[keyof GetMonthResponses];

export type AssignToBucketData = {
    body: AssignRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Month
         */
        month: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/months/{month}/assign';
};

export type AssignToBucketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignToBucketError = AssignToBucketErrors[keyof AssignToBucketErrors];

export type AssignToBucketResponses = {
    /**
     * Successful Response
     */
    200: MonthResponse;
};

export type AssignToBucketResponse = AssignToBucketResponses[keyof AssignToBucketResponses];

export type PutBucketData = {
    body: BucketInput;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Bucket Id
         */
        bucket_id: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/buckets/{bucket_id}';
};

export type PutBucketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutBucketError = PutBucketErrors[keyof PutBucketErrors];

export type PutBucketResponses = {
    /**
     * Successful Response
     */
    200: BucketOutput;
};

export type PutBucketResponse = PutBucketResponses[keyof PutBucketResponses];

export type ListBucketsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: {
        /**
         * Person
         */
        person?: string | null;
    };
    url: '/api/v1/budgets/{budget}/buckets';
};

export type ListBucketsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBucketsError = ListBucketsErrors[keyof ListBucketsErrors];

export type ListBucketsResponses = {
    /**
     * Response Listbuckets
     *
     * Successful Response
     */
    200: Array<BucketOutput>;
};

export type ListBucketsResponse = ListBucketsResponses[keyof ListBucketsResponses];

export type GetBalancesData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/balances';
};

export type GetBalancesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBalancesError = GetBalancesErrors[keyof GetBalancesErrors];

export type GetBalancesResponses = {
    /**
     * Successful Response
     */
    200: BalanceSheet;
};

export type GetBalancesResponse = GetBalancesResponses[keyof GetBalancesResponses];

export type SettleUpData = {
    body: SettleRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/settle';
};

export type SettleUpErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SettleUpError = SettleUpErrors[keyof SettleUpErrors];

export type SettleUpResponses = {
    /**
     * Successful Response
     */
    200: EntryResponse;
};

export type SettleUpResponse = SettleUpResponses[keyof SettleUpResponses];

export type ListEntriesData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: {
        /**
         * Month
         */
        month?: string | null;
        /**
         * Person
         */
        person?: string | null;
        /**
         * Bucket
         */
        bucket?: string | null;
        /**
         * Tag
         */
        tag?: string | null;
        /**
         * Payee
         */
        payee?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/budgets/{budget}/entries';
};

export type ListEntriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEntriesError = ListEntriesErrors[keyof ListEntriesErrors];

export type ListEntriesResponses = {
    /**
     * Successful Response
     */
    200: EntryList;
};

export type ListEntriesResponse = ListEntriesResponses[keyof ListEntriesResponses];

export type CreateEntryData = {
    body: EntryCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/entries';
};

export type CreateEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEntryError = CreateEntryErrors[keyof CreateEntryErrors];

export type CreateEntryResponses = {
    /**
     * Successful Response
     */
    200: EntryResponse;
};

export type CreateEntryResponse = CreateEntryResponses[keyof CreateEntryResponses];

export type DeleteEntryData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/entries/{entry_id}';
};

export type DeleteEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEntryError = DeleteEntryErrors[keyof DeleteEntryErrors];

export type DeleteEntryResponses = {
    /**
     * Successful Response
     */
    200: EntryResponse;
};

export type DeleteEntryResponse = DeleteEntryResponses[keyof DeleteEntryResponses];

export type GetEntryData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/entries/{entry_id}';
};

export type GetEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntryError = GetEntryErrors[keyof GetEntryErrors];

export type GetEntryResponses = {
    /**
     * Successful Response
     */
    200: Entry;
};

export type GetEntryResponse = GetEntryResponses[keyof GetEntryResponses];

export type UpdateEntryData = {
    body: EntryUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/entries/{entry_id}';
};

export type UpdateEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEntryError = UpdateEntryErrors[keyof UpdateEntryErrors];

export type UpdateEntryResponses = {
    /**
     * Successful Response
     */
    200: EntryResponse;
};

export type UpdateEntryResponse = UpdateEntryResponses[keyof UpdateEntryResponses];

export type GetEntryHistoryData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/entries/{entry_id}/history';
};

export type GetEntryHistoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntryHistoryError = GetEntryHistoryErrors[keyof GetEntryHistoryErrors];

export type GetEntryHistoryResponses = {
    /**
     * Successful Response
     */
    200: HistoryList;
};

export type GetEntryHistoryResponse = GetEntryHistoryResponses[keyof GetEntryHistoryResponses];

export type PreviewSplitData = {
    body: EntryCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/entries/preview';
};

export type PreviewSplitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PreviewSplitError = PreviewSplitErrors[keyof PreviewSplitErrors];

export type PreviewSplitResponses = {
    /**
     * Successful Response
     */
    200: SplitPreview;
};

export type PreviewSplitResponse = PreviewSplitResponses[keyof PreviewSplitResponses];

export type ListRulesData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/rules';
};

export type ListRulesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRulesError = ListRulesErrors[keyof ListRulesErrors];

export type ListRulesResponses = {
    /**
     * Response Listrules
     *
     * Successful Response
     */
    200: Array<RuleOutput>;
};

export type ListRulesResponse = ListRulesResponses[keyof ListRulesResponses];

export type PutRulesData = {
    /**
     * Body
     */
    body: Array<RuleInput>;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/rules';
};

export type PutRulesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutRulesError = PutRulesErrors[keyof PutRulesErrors];

export type PutRulesResponses = {
    /**
     * Response Putrules
     *
     * Successful Response
     */
    200: Array<RuleOutput>;
};

export type PutRulesResponse = PutRulesResponses[keyof PutRulesResponses];

export type GetMeData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type GetMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type ListApiKeysData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/me/keys';
};

export type ListApiKeysErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListApiKeysError = ListApiKeysErrors[keyof ListApiKeysErrors];

export type ListApiKeysResponses = {
    /**
     * Response Listapikeys
     *
     * Successful Response
     */
    200: Array<ApiKeyResponse>;
};

export type ListApiKeysResponse = ListApiKeysResponses[keyof ListApiKeysResponses];

export type CreateApiKeyData = {
    body: ApiKeyCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/me/keys';
};

export type CreateApiKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApiKeyError = CreateApiKeyErrors[keyof CreateApiKeyErrors];

export type CreateApiKeyResponses = {
    /**
     * Successful Response
     */
    201: ApiKeyCreated;
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type DeleteApiKeyData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Key Id
         */
        key_id: number;
    };
    query?: never;
    url: '/api/v1/me/keys/{key_id}';
};

export type DeleteApiKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiKeyError = DeleteApiKeyErrors[keyof DeleteApiKeyErrors];

export type DeleteApiKeyResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiKeyResponse = DeleteApiKeyResponses[keyof DeleteApiKeyResponses];
