// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ApiKeyCreate
 */
export type ApiKeyCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Scopes
     */
    scopes?: Array<string>;
    /**
     * Expires In Days
     */
    expires_in_days?: number | null;
};

/**
 * ApiKeyCreated
 */
export type ApiKeyCreated = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Scopes
     */
    scopes: Array<string>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Last Used At
     */
    last_used_at: string | null;
    /**
     * Token
     *
     * Shown once. It cannot be retrieved again.
     */
    token: string;
};

/**
 * ApiKeyResponse
 */
export type ApiKeyResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Scopes
     */
    scopes: Array<string>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Last Used At
     */
    last_used_at: string | null;
};

/**
 * AssignRequest
 */
export type AssignRequest = {
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Amount
     */
    amount: number | string;
};

/**
 * AuthConfig
 */
export type AuthConfig = {
    /**
     * Login Url
     */
    login_url: string;
};

/**
 * AutoAssignRequest
 */
export type AutoAssignRequest = {
    /**
     * Strategy
     *
     * How much to put in each bucket
     */
    strategy: string;
    /**
     * Buckets
     *
     * Limit to these buckets; all of them when omitted
     */
    buckets?: Array<string> | null;
};

/**
 * Balance
 */
export type Balance = {
    /**
     * Person
     */
    person: string;
    /**
     * Net
     */
    net: string;
};

/**
 * BalanceSheet
 */
export type BalanceSheet = {
    /**
     * Currency
     */
    currency: string;
    /**
     * Balances
     */
    balances: Array<Balance>;
    /**
     * Settle Up
     */
    settle_up: Array<Settlement>;
};

/**
 * Bucket
 *
 * One shared envelope. Several people fund it; anyone can spend against it.
 *
 * `split` and funding are deliberately independent. How much you put in this month is a
 * cashflow decision; what proportion of this category's spending is *yours* is a fairness
 * decision, and letting the first decide the second means you cannot fund a bucket generously
 * one month without also taking on more of its cost.
 *
 * Keeping them apart is what allows an envelope to be in the red for one person and in the
 * black for another: their position is what they funded minus what they bear.
 */
export type BucketInput = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Group
     */
    group?: string | null;
    target?: TargetInput | null;
    /**
     * Archived
     */
    archived?: boolean;
    /**
     * Order
     *
     * Sort position within its group; ties fall back to name
     */
    order?: number;
    /**
     * Split
     *
     * Fraction of spending each person bears. Empty means split evenly.
     */
    split?: {
        [key: string]: unknown | number | string;
    };
};

/**
 * Bucket
 *
 * One shared envelope. Several people fund it; anyone can spend against it.
 *
 * `split` and funding are deliberately independent. How much you put in this month is a
 * cashflow decision; what proportion of this category's spending is *yours* is a fairness
 * decision, and letting the first decide the second means you cannot fund a bucket generously
 * one month without also taking on more of its cost.
 *
 * Keeping them apart is what allows an envelope to be in the red for one person and in the
 * black for another: their position is what they funded minus what they bear.
 */
export type BucketOutput = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Group
     */
    group?: string | null;
    target?: TargetOutput | null;
    /**
     * Archived
     */
    archived?: boolean;
    /**
     * Order
     *
     * Sort position within its group; ties fall back to name
     */
    order?: number;
    /**
     * Split
     *
     * Fraction of spending each person bears. Empty means split evenly.
     */
    split?: {
        [key: string]: unknown | string;
    };
};

/**
 * BucketPosition
 */
export type BucketPosition = {
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Group
     */
    group?: string | null;
};

/**
 * BucketState
 *
 * A shared bucket, totalled for the household and broken down per funder.
 */
export type BucketState = {
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Name
     */
    name: string;
    /**
     * Group
     */
    group: string | null;
    /**
     * Assigned
     */
    assigned: string;
    /**
     * Activity
     */
    activity: string;
    /**
     * Available
     */
    available: string;
    /**
     * Target
     */
    target: string | null;
    /**
     * Funders
     */
    funders?: Array<FunderState>;
};

/**
 * BudgetConnect
 */
export type BudgetConnect = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Repo
     *
     * owner/repo on GitHub
     */
    repo: string;
};

/**
 * BudgetCreate
 *
 * Everything needed to go from no budget at all to a working one.
 */
export type BudgetCreate = {
    /**
     * Name
     *
     * What to call this budget
     */
    name: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Repo
     *
     * A new repo name to create, or an existing owner/repo to initialize
     */
    repo: string;
    /**
     * Person
     *
     * Your id within this budget; appears in every split
     */
    person: string;
    /**
     * Display Name
     *
     * Your name on screen
     */
    display_name: string;
    /**
     * Buckets
     *
     * Buckets to start with; a default set is used when omitted
     */
    buckets?: Array<BucketInput> | null;
};

/**
 * BudgetJoin
 *
 * Adding yourself to a budget whose repo you can already push to.
 */
export type BudgetJoin = {
    /**
     * Person
     */
    person: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Buckets
     */
    buckets?: Array<BucketInput> | null;
};

/**
 * BudgetSummary
 */
export type BudgetSummary = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Repo
     */
    repo: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Branch
     */
    branch: string;
    /**
     * Members
     */
    members: Array<Member>;
    /**
     * Me
     *
     * Which member the caller is, if any
     */
    me: string | null;
    /**
     * Can Write
     */
    can_write: boolean;
};

/**
 * Cadence
 */
export type Cadence = 'weekly' | 'monthly' | 'yearly';

/**
 * CollaboratorResponse
 */
export type CollaboratorResponse = {
    /**
     * Login
     */
    login: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * Permission
     */
    permission: string;
    /**
     * Invited
     *
     * Invitation sent but not yet accepted
     */
    invited: boolean;
    /**
     * Is Member
     *
     * Already listed in the budget's members
     */
    is_member: boolean;
};

/**
 * CommitRef
 */
export type CommitRef = {
    /**
     * Sha
     */
    sha: string;
    /**
     * Subject
     */
    subject: string;
    /**
     * Author Name
     */
    author_name: string;
    /**
     * Date
     */
    date: string;
};

/**
 * DevicePoll
 */
export type DevicePoll = {
    /**
     * Device Code
     */
    device_code: string;
    /**
     * Name
     */
    name?: string;
};

/**
 * DeviceResult
 */
export type DeviceResult = {
    /**
     * Status
     */
    status: string;
    /**
     * Token
     */
    token?: string | null;
    /**
     * Login
     */
    login?: string | null;
};

/**
 * DeviceStart
 */
export type DeviceStart = {
    /**
     * Device Code
     */
    device_code: string;
    /**
     * User Code
     */
    user_code: string;
    /**
     * Verification Uri
     */
    verification_uri: string;
    /**
     * Interval
     */
    interval: number;
};

/**
 * DueEntry
 */
export type DueEntry = {
    /**
     * Scheduled Id
     */
    scheduled_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Payee
     */
    payee: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    kind: EntryKind;
    /**
     * Date
     */
    date: string;
    /**
     * Overdue
     *
     * Its date has already passed
     */
    overdue: boolean;
};

/**
 * DueList
 */
export type DueList = {
    /**
     * Due
     */
    due: Array<DueEntry>;
    /**
     * Through
     *
     * How far ahead this list looked
     */
    through: string;
};

/**
 * Entry
 */
export type Entry = {
    /**
     * Id
     */
    id: string;
    kind?: EntryKind;
    /**
     * Date
     */
    date: string;
    /**
     * At
     */
    at?: string | null;
    /**
     * Payee
     */
    payee: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Paid By
     */
    paid_by: {
        [key: string]: unknown | string;
    };
    /**
     * Shares
     */
    shares: Array<ShareOutput>;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Rule
     */
    rule?: string | null;
    /**
     * Items
     *
     * Receipt lines; must sum to the entry amount
     */
    items?: Array<LineItem>;
    place?: Place | null;
};

/**
 * EntryCreate
 */
export type EntryCreate = {
    /**
     * Amount
     *
     * Negative for money out, positive for money in
     */
    amount: number | string;
    /**
     * Payee
     */
    payee: string;
    /**
     * Date
     *
     * Defaults to today
     */
    date?: string | null;
    /**
     * At
     *
     * Wall-clock moment it happened. Defaults to now; used for time patterns.
     */
    at?: string | null;
    kind?: EntryKind;
    /**
     * Currency
     *
     * Defaults to the budget currency
     */
    currency?: string | null;
    /**
     * Paid By
     *
     * Defaults to the whole amount from the calling user
     */
    paid_by?: {
        [key: string]: number | string;
    } | null;
    /**
     * Shares
     *
     * Explicit split. When omitted, rules decide.
     */
    shares?: Array<ShareInputInput> | null;
    /**
     * Bucket
     *
     * Book every share against this bucket, overriding the rule
     */
    bucket?: string | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Items
     *
     * Receipt lines; must sum to the entry amount
     */
    items?: Array<LineItemInputInput> | null;
    place?: PlaceInput | null;
};

/**
 * EntryKind
 */
export type EntryKind = 'expense' | 'income' | 'transfer' | 'settlement';

/**
 * EntryList
 */
export type EntryList = {
    /**
     * Entries
     */
    entries: Array<Entry>;
    /**
     * Total
     */
    total: number;
};

/**
 * EntryResponse
 */
export type EntryResponse = {
    entry: Entry;
    /**
     * Commit
     *
     * Sha of the commit that recorded this change
     */
    commit: string;
};

/**
 * EntryUpdate
 */
export type EntryUpdate = {
    /**
     * Amount
     */
    amount?: number | string | null;
    /**
     * Payee
     */
    payee?: string | null;
    /**
     * Date
     */
    date?: string | null;
    /**
     * Paid By
     */
    paid_by?: {
        [key: string]: number | string;
    } | null;
    /**
     * Shares
     */
    shares?: Array<ShareInputInput> | null;
    /**
     * Items
     */
    items?: Array<LineItemInputInput> | null;
    place?: PlaceInput | null;
    /**
     * At
     */
    at?: string | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
};

/**
 * FunderState
 *
 * One person's standing in one shared bucket.
 *
 * `available` can be negative while another funder's is positive — that is the point of
 * separating funding from split. It means this person is consuming more of the category than
 * they have put in, which is fixed by funding more or by changing the split, and is a
 * different problem from owing somebody cash.
 */
export type FunderState = {
    /**
     * Person
     */
    person: string;
    /**
     * Split
     *
     * Fraction of this bucket's spending they bear
     */
    split: string;
    /**
     * Assigned
     *
     * What they put in this month
     */
    assigned: string;
    /**
     * Activity
     *
     * What they bore this month; negative for spending
     */
    activity: string;
    /**
     * Available
     *
     * Their carried position: funded minus borne
     */
    available: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HistoryDetail
 *
 * One change, in enough detail to decide whether to undo it.
 */
export type HistoryDetail = {
    /**
     * Sha
     */
    sha: string;
    /**
     * Subject
     */
    subject: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Author
     */
    author: string;
    /**
     * Actor
     */
    actor: string | null;
    /**
     * Date
     */
    date: string;
    /**
     * Entry Id
     */
    entry_id: string | null;
    /**
     * Person
     *
     * Whose buckets or assignments moved
     */
    person?: string | null;
    /**
     * Month
     */
    month?: string | null;
    /**
     * Mine
     */
    mine: boolean;
    /**
     * Reverts
     *
     * Sha this change undid, if any
     */
    reverts?: string | null;
    /**
     * Reverted By
     *
     * Sha that undid this change; set means it is no longer applied
     */
    reverted_by?: string | null;
    /**
     * Files
     */
    files: Array<HistoryFileChange>;
    /**
     * Diff
     *
     * Unified patch, possibly truncated
     */
    diff: string;
    /**
     * Diff Truncated
     */
    diff_truncated: boolean;
    /**
     * Can Undo
     *
     * False when it is already undone, or you have read-only access
     */
    can_undo: boolean;
};

/**
 * HistoryEvent
 */
export type HistoryEvent = {
    /**
     * Sha
     */
    sha: string;
    /**
     * Subject
     */
    subject: string;
    /**
     * Kind
     *
     * entry, assignment, bucket, rules, members, note, undo
     */
    kind: string;
    /**
     * Author
     */
    author: string;
    /**
     * Actor
     */
    actor: string | null;
    /**
     * Date
     */
    date: string;
    /**
     * Entry Id
     */
    entry_id: string | null;
    /**
     * Mine
     *
     * You made this change
     */
    mine: boolean;
    /**
     * Reverts
     *
     * Sha this change undid, if any
     */
    reverts?: string | null;
};

/**
 * HistoryFileChange
 */
export type HistoryFileChange = {
    /**
     * Path
     */
    path: string;
    /**
     * Status
     *
     * added, modified or removed
     */
    status: string;
    /**
     * Added
     *
     * Lines added
     */
    added: number;
    /**
     * Removed
     *
     * Lines removed
     */
    removed: number;
};

/**
 * HistoryList
 */
export type HistoryList = {
    /**
     * Commits
     */
    commits: Array<CommitRef>;
};

/**
 * HistoryPage
 */
export type HistoryPage = {
    /**
     * Events
     */
    events: Array<HistoryEvent>;
    /**
     * Undoable
     *
     * What undo would revert, if anything
     */
    undoable: string | null;
    /**
     * Redoable
     *
     * Set only while your last change was an undo
     */
    redoable?: string | null;
};

/**
 * InviteRequest
 */
export type InviteRequest = {
    /**
     * Login
     *
     * GitHub login
     */
    login: string;
    /**
     * Name
     *
     * Display name; defaults to the login
     */
    name?: string | null;
    /**
     * Person
     *
     * Person id; derived from the login
     */
    person?: string | null;
};

/**
 * InviteResponse
 */
export type InviteResponse = {
    /**
     * Login
     */
    login: string;
    /**
     * Invited
     *
     * False when they already had repo access
     */
    invited: boolean;
    /**
     * Person
     */
    person: string;
};

/**
 * LineItem
 *
 * One line on a receipt.
 *
 * A receipt is one payment but several things bought, and they do not always belong in the
 * same envelope or to the same person — a supermarket run is groceries and a bottle of wine.
 * Splitting the *entry* cannot express that, because the entry's split is about the total.
 *
 * A line carries its own shares when it needs to. When it does not, it simply belongs to
 * whatever the entry as a whole decided.
 */
export type LineItem = {
    /**
     * Label
     */
    label: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Quantity
     */
    quantity?: string | null;
    /**
     * Shares
     */
    shares?: Array<ShareOutput>;
};

/**
 * LineItemInput
 */
export type LineItemInputInput = {
    /**
     * Label
     */
    label: string;
    /**
     * Amount
     */
    amount: number | string;
    /**
     * Quantity
     */
    quantity?: number | string | null;
    /**
     * Shares
     */
    shares?: Array<ShareInputInput> | null;
};

/**
 * LineItemInput
 */
export type LineItemInputOutput = {
    /**
     * Label
     */
    label: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Quantity
     */
    quantity?: string | null;
    /**
     * Shares
     */
    shares?: Array<ShareInputOutput> | null;
};

/**
 * Match
 *
 * An empty match matches everything, which is how a catch-all default is written.
 */
export type MatchInput = {
    /**
     * Payee Contains
     */
    payee_contains?: string | null;
    /**
     * Tag
     */
    tag?: string | null;
    /**
     * Paid By
     */
    paid_by?: string | null;
    /**
     * Min Amount
     */
    min_amount?: number | string | null;
};

/**
 * Match
 *
 * An empty match matches everything, which is how a catch-all default is written.
 */
export type MatchOutput = {
    /**
     * Payee Contains
     */
    payee_contains?: string | null;
    /**
     * Tag
     */
    tag?: string | null;
    /**
     * Paid By
     */
    paid_by?: string | null;
    /**
     * Min Amount
     */
    min_amount?: string | null;
};

/**
 * Member
 */
export type Member = {
    /**
     * Person
     */
    person: string;
    /**
     * Name
     */
    name: string;
    /**
     * Github
     *
     * Their GitHub login. A member without one is a placeholder, not an account.
     */
    github?: string | null;
};

/**
 * MonthResponse
 */
export type MonthResponse = {
    /**
     * Person
     */
    person: string;
    /**
     * Month
     */
    month: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Ready To Assign
     */
    ready_to_assign: string;
    /**
     * Income
     */
    income: string;
    /**
     * Assigned
     */
    assigned: string;
    /**
     * Buckets
     */
    buckets: Array<BucketState>;
};

/**
 * MoveRequest
 */
export type MoveRequest = {
    /**
     * Source
     *
     * Bucket the money leaves
     */
    source: string;
    /**
     * Target
     *
     * Bucket the money goes to
     */
    target: string;
    /**
     * Amount
     */
    amount: number | string;
};

/**
 * NearbyPlaceResponse
 */
export type NearbyPlaceResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Kind
     */
    kind: string | null;
    /**
     * Lat
     */
    lat: number;
    /**
     * Lon
     */
    lon: number;
    /**
     * Address
     */
    address?: string | null;
};

/**
 * NoteBody
 */
export type NoteBody = {
    /**
     * Text
     *
     * Markdown. Empty removes the note.
     */
    text: string;
};

/**
 * NoteResponse
 */
export type NoteResponse = {
    /**
     * Entry Id
     */
    entry_id: string;
    /**
     * Text
     */
    text: string;
};

/**
 * PayeeSuggestion
 */
export type PayeeSuggestion = {
    /**
     * Payee
     */
    payee: string;
    /**
     * Count
     *
     * How many times this payee appears
     */
    count: number;
    /**
     * Last Used
     */
    last_used: string;
    /**
     * Amount
     *
     * Typical amount: the mode, else the most recent
     */
    amount: string | null;
    /**
     * Bucket
     *
     * Bucket most often used for this payee
     */
    bucket: string | null;
    /**
     * Basis
     *
     * Which rule produced the suggestion, for the explanation
     */
    basis: string;
};

/**
 * Place
 *
 * Where a payment happened.
 *
 * Coordinates are committed to the budget repo, which is a deliberate choice: it makes the
 * suggestions work on every device and survive clearing a browser. It also means the repo
 * holds a durable, shared record of where you have been — see specs/data-model.md.
 */
export type Place = {
    /**
     * Lat
     */
    lat: number;
    /**
     * Lon
     */
    lon: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Provider Id
     */
    provider_id?: string | null;
};

/**
 * PlaceInput
 */
export type PlaceInput = {
    /**
     * Lat
     */
    lat: number;
    /**
     * Lon
     */
    lon: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Provider Id
     */
    provider_id?: string | null;
};

/**
 * PostRequest
 */
export type PostRequest = {
    /**
     * Date
     *
     * Defaults to today
     */
    date?: string | null;
};

/**
 * Recurrence
 *
 * How often something repeats.
 *
 * Three cadences cover what a household actually has: a salary and rent monthly, a cleaner
 * weekly, insurance yearly. More exotic rules can be added when something real needs one.
 */
export type Recurrence = {
    cadence: Cadence;
    /**
     * Day
     *
     * Day of the month, for monthly and yearly
     */
    day?: number | null;
    /**
     * Weekday
     *
     * Monday is 0, for weekly
     */
    weekday?: number | null;
    /**
     * Month
     *
     * Month, for yearly
     */
    month?: number | null;
    /**
     * Interval
     *
     * Every N periods; 2 with a monthly cadence is every other month
     */
    interval?: number;
};

/**
 * ReorderRequest
 *
 * The buckets a drag moved, in the order they should end up.
 *
 * Position within a group is the index in this list, not a number the client sends: a client
 * computing its own indices can produce a sequence that disagrees with itself, and the order
 * it displays is the only thing it actually knows.
 */
export type ReorderRequest = {
    /**
     * Order
     */
    order: Array<BucketPosition>;
};

/**
 * RepoOption
 */
export type RepoOption = {
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Private
     */
    private: boolean;
    /**
     * Description
     */
    description: string | null;
    /**
     * Is Budget
     *
     * Has a budget.yaml, so it is ready to connect
     */
    is_budget: boolean;
    /**
     * Connected
     *
     * Already connected as a budget here
     */
    connected: boolean;
};

/**
 * Rule
 */
export type RuleInput = {
    /**
     * Id
     */
    id: string;
    when?: MatchInput;
    /**
     * Bucket
     *
     * Which bucket a matching entry belongs in
     */
    bucket: string;
};

/**
 * Rule
 */
export type RuleOutput = {
    /**
     * Id
     */
    id: string;
    when?: MatchOutput;
    /**
     * Bucket
     *
     * Which bucket a matching entry belongs in
     */
    bucket: string;
};

/**
 * Scheduled
 *
 * A template plus a recurrence: rent, a salary, a subscription.
 *
 * It holds the same two-sided split an entry does, so posting one produces an ordinary
 * entry with nothing inferred at post time. `last_posted` is what stops the same charge
 * being offered twice.
 */
export type ScheduledInput = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    kind?: EntryKind;
    /**
     * Payee
     */
    payee: string;
    /**
     * Amount
     */
    amount: number | string;
    /**
     * Currency
     */
    currency: string;
    recurrence: Recurrence;
    /**
     * Starts
     */
    starts: string;
    /**
     * Ends
     */
    ends?: string | null;
    /**
     * Last Posted
     */
    last_posted?: string | null;
    /**
     * Paused
     */
    paused?: boolean;
    /**
     * Paid By
     */
    paid_by?: {
        [key: string]: unknown | number | string;
    };
    /**
     * Shares
     */
    shares?: Array<ShareInput>;
    /**
     * Bucket
     *
     * Where an expense lands when no explicit split is given
     */
    bucket?: string | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
};

/**
 * Scheduled
 *
 * A template plus a recurrence: rent, a salary, a subscription.
 *
 * It holds the same two-sided split an entry does, so posting one produces an ordinary
 * entry with nothing inferred at post time. `last_posted` is what stops the same charge
 * being offered twice.
 */
export type ScheduledOutput = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    kind?: EntryKind;
    /**
     * Payee
     */
    payee: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Currency
     */
    currency: string;
    recurrence: Recurrence;
    /**
     * Starts
     */
    starts: string;
    /**
     * Ends
     */
    ends?: string | null;
    /**
     * Last Posted
     */
    last_posted?: string | null;
    /**
     * Paused
     */
    paused?: boolean;
    /**
     * Paid By
     */
    paid_by?: {
        [key: string]: unknown | string;
    };
    /**
     * Shares
     */
    shares?: Array<ShareOutput>;
    /**
     * Bucket
     *
     * Where an expense lands when no explicit split is given
     */
    bucket?: string | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
};

/**
 * SettleRequest
 */
export type SettleRequest = {
    /**
     * To
     *
     * Person id being paid
     */
    to: string;
    /**
     * Amount
     */
    amount: number | string;
    /**
     * Payer
     *
     * Person id who handed over the money. Defaults to the calling user.
     */
    payer?: string | null;
    /**
     * Date
     */
    date?: string | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * Settlement
 *
 * One suggested payment that reduces outstanding debt.
 */
export type Settlement = {
    /**
     * Payer
     */
    payer: string;
    /**
     * Payee
     */
    payee: string;
    /**
     * Amount
     */
    amount: string;
};

/**
 * Share
 *
 * One person's slice of an entry, booked against one of *their* buckets.
 *
 * A person may hold several shares in one entry when they split their own slice across
 * buckets, so this is not keyed by person.
 */
export type ShareInput = {
    /**
     * Person
     */
    person: string;
    /**
     * Amount
     */
    amount: number | string;
    /**
     * Bucket
     */
    bucket?: string | null;
};

/**
 * Share
 *
 * One person's slice of an entry, booked against one of *their* buckets.
 *
 * A person may hold several shares in one entry when they split their own slice across
 * buckets, so this is not keyed by person.
 */
export type ShareOutput = {
    /**
     * Person
     */
    person: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Bucket
     */
    bucket?: string | null;
};

/**
 * ShareInput
 */
export type ShareInputInput = {
    /**
     * Person
     */
    person: string;
    /**
     * Amount
     */
    amount: number | string;
    /**
     * Bucket
     */
    bucket?: string | null;
};

/**
 * ShareInput
 */
export type ShareInputOutput = {
    /**
     * Person
     */
    person: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Bucket
     */
    bucket?: string | null;
};

/**
 * SplitPreview
 */
export type SplitPreview = {
    /**
     * Rule
     */
    rule: string | null;
    /**
     * Shares
     */
    shares: Array<ShareInputOutput>;
};

/**
 * SuggestionResponse
 */
export type SuggestionResponse = {
    /**
     * Payee
     */
    payee: string | null;
    /**
     * Amount
     */
    amount: string | null;
    /**
     * Bucket
     */
    bucket: string | null;
    /**
     * Shares
     */
    shares: Array<ShareInputOutput>;
    /**
     * Items
     */
    items: Array<LineItemInputOutput>;
    /**
     * Place Name
     */
    place_name: string | null;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Basis
     *
     * payee, place, time or none
     */
    basis: string;
    /**
     * Reason
     *
     * Why this was suggested; shown on hover
     */
    reason: string;
    /**
     * Sample Size
     */
    sample_size: number;
};

/**
 * Target
 */
export type TargetInput = {
    /**
     * Kind
     */
    kind: string;
    /**
     * Amount
     */
    amount?: number | string | null;
    /**
     * Due
     */
    due?: string | null;
};

/**
 * Target
 */
export type TargetOutput = {
    /**
     * Kind
     */
    kind: string;
    /**
     * Amount
     */
    amount?: string | null;
    /**
     * Due
     */
    due?: string | null;
};

/**
 * UndoResult
 */
export type UndoResult = {
    /**
     * Undone Sha
     */
    undone_sha: string;
    /**
     * Undone Subject
     *
     * What was reverted, for the confirmation
     */
    undone_subject: string;
    /**
     * Commit
     */
    commit: string;
    /**
     * Can Redo
     */
    can_redo: boolean;
};

/**
 * UserOption
 */
export type UserOption = {
    /**
     * Login
     */
    login: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Login
     */
    login: string;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetAuthConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/config';
};

export type GetAuthConfigResponses = {
    /**
     * Successful Response
     */
    200: AuthConfig;
};

export type GetAuthConfigResponse = GetAuthConfigResponses[keyof GetAuthConfigResponses];

export type StartGithubLoginData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return Host
         */
        return_host?: string | null;
    };
    url: '/api/v1/auth/github/start';
};

export type StartGithubLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartGithubLoginError = StartGithubLoginErrors[keyof StartGithubLoginErrors];

export type StartGithubLoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FinishGithubLoginData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
        /**
         * State
         */
        state: string;
    };
    url: '/api/v1/auth/github/callback';
};

export type FinishGithubLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FinishGithubLoginError = FinishGithubLoginErrors[keyof FinishGithubLoginErrors];

export type FinishGithubLoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AcceptHandoffData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Ticket
         */
        ticket: string;
    };
    url: '/api/v1/auth/handoff';
};

export type AcceptHandoffErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AcceptHandoffError = AcceptHandoffErrors[keyof AcceptHandoffErrors];

export type AcceptHandoffResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type StartDeviceLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/device/start';
};

export type StartDeviceLoginResponses = {
    /**
     * Successful Response
     */
    200: DeviceStart;
};

export type StartDeviceLoginResponse = StartDeviceLoginResponses[keyof StartDeviceLoginResponses];

export type PollDeviceLoginData = {
    body: DevicePoll;
    path?: never;
    query?: never;
    url: '/api/v1/auth/device/poll';
};

export type PollDeviceLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PollDeviceLoginError = PollDeviceLoginErrors[keyof PollDeviceLoginErrors];

export type PollDeviceLoginResponses = {
    /**
     * Successful Response
     */
    200: DeviceResult;
};

export type PollDeviceLoginResponse = PollDeviceLoginResponses[keyof PollDeviceLoginResponses];

export type ListBudgetsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/budgets';
};

export type ListBudgetsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBudgetsError = ListBudgetsErrors[keyof ListBudgetsErrors];

export type ListBudgetsResponses = {
    /**
     * Response Listbudgets
     *
     * Successful Response
     */
    200: Array<BudgetSummary>;
};

export type ListBudgetsResponse = ListBudgetsResponses[keyof ListBudgetsResponses];

export type ConnectBudgetData = {
    body: BudgetConnect;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/budgets';
};

export type ConnectBudgetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConnectBudgetError = ConnectBudgetErrors[keyof ConnectBudgetErrors];

export type ConnectBudgetResponses = {
    /**
     * Successful Response
     */
    201: BudgetSummary;
};

export type ConnectBudgetResponse = ConnectBudgetResponses[keyof ConnectBudgetResponses];

export type CreateBudgetData = {
    body: BudgetCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/budgets/create';
};

export type CreateBudgetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateBudgetError = CreateBudgetErrors[keyof CreateBudgetErrors];

export type CreateBudgetResponses = {
    /**
     * Successful Response
     */
    201: BudgetSummary;
};

export type CreateBudgetResponse = CreateBudgetResponses[keyof CreateBudgetResponses];

export type GetBudgetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}';
};

export type GetBudgetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBudgetError = GetBudgetErrors[keyof GetBudgetErrors];

export type GetBudgetResponses = {
    /**
     * Successful Response
     */
    200: BudgetSummary;
};

export type GetBudgetResponse = GetBudgetResponses[keyof GetBudgetResponses];

export type ListMembersData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/members';
};

export type ListMembersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMembersError = ListMembersErrors[keyof ListMembersErrors];

export type ListMembersResponses = {
    /**
     * Response Listmembers
     *
     * Successful Response
     */
    200: Array<Member>;
};

export type ListMembersResponse = ListMembersResponses[keyof ListMembersResponses];

export type PutMembersData = {
    /**
     * Body
     */
    body: Array<Member>;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/members';
};

export type PutMembersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutMembersError = PutMembersErrors[keyof PutMembersErrors];

export type PutMembersResponses = {
    /**
     * Response Putmembers
     *
     * Successful Response
     */
    200: Array<Member>;
};

export type PutMembersResponse = PutMembersResponses[keyof PutMembersResponses];

export type JoinBudgetData = {
    body: BudgetJoin;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/members/me';
};

export type JoinBudgetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JoinBudgetError = JoinBudgetErrors[keyof JoinBudgetErrors];

export type JoinBudgetResponses = {
    /**
     * Successful Response
     */
    201: BudgetSummary;
};

export type JoinBudgetResponse = JoinBudgetResponses[keyof JoinBudgetResponses];

export type GetMonthData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Month
         */
        month: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: {
        /**
         * Person
         */
        person?: string | null;
    };
    url: '/api/v1/budgets/{budget}/months/{month}';
};

export type GetMonthErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonthError = GetMonthErrors[keyof GetMonthErrors];

export type GetMonthResponses = {
    /**
     * Successful Response
     */
    200: MonthResponse;
};

export type GetMonthResponse = GetMonthResponses[keyof GetMonthResponses];

export type AssignToBucketData = {
    body: AssignRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Month
         */
        month: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/months/{month}/assign';
};

export type AssignToBucketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignToBucketError = AssignToBucketErrors[keyof AssignToBucketErrors];

export type AssignToBucketResponses = {
    /**
     * Successful Response
     */
    200: MonthResponse;
};

export type AssignToBucketResponse = AssignToBucketResponses[keyof AssignToBucketResponses];

export type AutoAssignData = {
    body: AutoAssignRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Month
         */
        month: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/months/{month}/auto-assign';
};

export type AutoAssignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AutoAssignError = AutoAssignErrors[keyof AutoAssignErrors];

export type AutoAssignResponses = {
    /**
     * Successful Response
     */
    200: MonthResponse;
};

export type AutoAssignResponse = AutoAssignResponses[keyof AutoAssignResponses];

export type MoveMoneyData = {
    body: MoveRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Month
         */
        month: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/months/{month}/move';
};

export type MoveMoneyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MoveMoneyError = MoveMoneyErrors[keyof MoveMoneyErrors];

export type MoveMoneyResponses = {
    /**
     * Successful Response
     */
    200: MonthResponse;
};

export type MoveMoneyResponse = MoveMoneyResponses[keyof MoveMoneyResponses];

export type ReorderBucketsData = {
    body: ReorderRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/buckets/order';
};

export type ReorderBucketsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReorderBucketsError = ReorderBucketsErrors[keyof ReorderBucketsErrors];

export type ReorderBucketsResponses = {
    /**
     * Response Reorderbuckets
     *
     * Successful Response
     */
    200: Array<BucketOutput>;
};

export type ReorderBucketsResponse = ReorderBucketsResponses[keyof ReorderBucketsResponses];

export type PutBucketData = {
    body: BucketInput;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Bucket Id
         */
        bucket_id: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/buckets/{bucket_id}';
};

export type PutBucketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutBucketError = PutBucketErrors[keyof PutBucketErrors];

export type PutBucketResponses = {
    /**
     * Successful Response
     */
    200: BucketOutput;
};

export type PutBucketResponse = PutBucketResponses[keyof PutBucketResponses];

export type ListBucketsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/buckets';
};

export type ListBucketsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBucketsError = ListBucketsErrors[keyof ListBucketsErrors];

export type ListBucketsResponses = {
    /**
     * Response Listbuckets
     *
     * Successful Response
     */
    200: Array<BucketOutput>;
};

export type ListBucketsResponse = ListBucketsResponses[keyof ListBucketsResponses];

export type GetBalancesData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/balances';
};

export type GetBalancesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBalancesError = GetBalancesErrors[keyof GetBalancesErrors];

export type GetBalancesResponses = {
    /**
     * Successful Response
     */
    200: BalanceSheet;
};

export type GetBalancesResponse = GetBalancesResponses[keyof GetBalancesResponses];

export type SettleUpData = {
    body: SettleRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/settle';
};

export type SettleUpErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SettleUpError = SettleUpErrors[keyof SettleUpErrors];

export type SettleUpResponses = {
    /**
     * Successful Response
     */
    200: EntryResponse;
};

export type SettleUpResponse = SettleUpResponses[keyof SettleUpResponses];

export type ListEntriesData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: {
        /**
         * Month
         */
        month?: string | null;
        /**
         * Person
         */
        person?: string | null;
        /**
         * Bucket
         */
        bucket?: string | null;
        /**
         * Tag
         */
        tag?: string | null;
        /**
         * Payee
         */
        payee?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/budgets/{budget}/entries';
};

export type ListEntriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEntriesError = ListEntriesErrors[keyof ListEntriesErrors];

export type ListEntriesResponses = {
    /**
     * Successful Response
     */
    200: EntryList;
};

export type ListEntriesResponse = ListEntriesResponses[keyof ListEntriesResponses];

export type CreateEntryData = {
    body: EntryCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/entries';
};

export type CreateEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEntryError = CreateEntryErrors[keyof CreateEntryErrors];

export type CreateEntryResponses = {
    /**
     * Successful Response
     */
    200: EntryResponse;
};

export type CreateEntryResponse = CreateEntryResponses[keyof CreateEntryResponses];

export type SuggestPayeesData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: {
        /**
         * Q
         */
        q?: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/budgets/{budget}/entries/payees';
};

export type SuggestPayeesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SuggestPayeesError = SuggestPayeesErrors[keyof SuggestPayeesErrors];

export type SuggestPayeesResponses = {
    /**
     * Response Suggestpayees
     *
     * Successful Response
     */
    200: Array<PayeeSuggestion>;
};

export type SuggestPayeesResponse = SuggestPayeesResponses[keyof SuggestPayeesResponses];

export type DeleteEntryData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/entries/{entry_id}';
};

export type DeleteEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEntryError = DeleteEntryErrors[keyof DeleteEntryErrors];

export type DeleteEntryResponses = {
    /**
     * Successful Response
     */
    200: EntryResponse;
};

export type DeleteEntryResponse = DeleteEntryResponses[keyof DeleteEntryResponses];

export type GetEntryData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/entries/{entry_id}';
};

export type GetEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntryError = GetEntryErrors[keyof GetEntryErrors];

export type GetEntryResponses = {
    /**
     * Successful Response
     */
    200: Entry;
};

export type GetEntryResponse = GetEntryResponses[keyof GetEntryResponses];

export type UpdateEntryData = {
    body: EntryUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/entries/{entry_id}';
};

export type UpdateEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEntryError = UpdateEntryErrors[keyof UpdateEntryErrors];

export type UpdateEntryResponses = {
    /**
     * Successful Response
     */
    200: EntryResponse;
};

export type UpdateEntryResponse = UpdateEntryResponses[keyof UpdateEntryResponses];

export type GetEntryHistoryData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/entries/{entry_id}/history';
};

export type GetEntryHistoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntryHistoryError = GetEntryHistoryErrors[keyof GetEntryHistoryErrors];

export type GetEntryHistoryResponses = {
    /**
     * Successful Response
     */
    200: HistoryList;
};

export type GetEntryHistoryResponse = GetEntryHistoryResponses[keyof GetEntryHistoryResponses];

export type GetEntryNoteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/entries/{entry_id}/note';
};

export type GetEntryNoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntryNoteError = GetEntryNoteErrors[keyof GetEntryNoteErrors];

export type GetEntryNoteResponses = {
    /**
     * Successful Response
     */
    200: NoteResponse;
};

export type GetEntryNoteResponse = GetEntryNoteResponses[keyof GetEntryNoteResponses];

export type PutEntryNoteData = {
    body: NoteBody;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/entries/{entry_id}/note';
};

export type PutEntryNoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutEntryNoteError = PutEntryNoteErrors[keyof PutEntryNoteErrors];

export type PutEntryNoteResponses = {
    /**
     * Successful Response
     */
    200: NoteResponse;
};

export type PutEntryNoteResponse = PutEntryNoteResponses[keyof PutEntryNoteResponses];

export type PreviewSplitData = {
    body: EntryCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/entries/preview';
};

export type PreviewSplitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PreviewSplitError = PreviewSplitErrors[keyof PreviewSplitErrors];

export type PreviewSplitResponses = {
    /**
     * Successful Response
     */
    200: SplitPreview;
};

export type PreviewSplitResponse = PreviewSplitResponses[keyof PreviewSplitResponses];

export type ListRulesData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/rules';
};

export type ListRulesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRulesError = ListRulesErrors[keyof ListRulesErrors];

export type ListRulesResponses = {
    /**
     * Response Listrules
     *
     * Successful Response
     */
    200: Array<RuleOutput>;
};

export type ListRulesResponse = ListRulesResponses[keyof ListRulesResponses];

export type PutRulesData = {
    /**
     * Body
     */
    body: Array<RuleInput>;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/rules';
};

export type PutRulesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutRulesError = PutRulesErrors[keyof PutRulesErrors];

export type PutRulesResponses = {
    /**
     * Response Putrules
     *
     * Successful Response
     */
    200: Array<RuleOutput>;
};

export type PutRulesResponse = PutRulesResponses[keyof PutRulesResponses];

export type GetMeData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type GetMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type ListApiKeysData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/me/keys';
};

export type ListApiKeysErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListApiKeysError = ListApiKeysErrors[keyof ListApiKeysErrors];

export type ListApiKeysResponses = {
    /**
     * Response Listapikeys
     *
     * Successful Response
     */
    200: Array<ApiKeyResponse>;
};

export type ListApiKeysResponse = ListApiKeysResponses[keyof ListApiKeysResponses];

export type CreateApiKeyData = {
    body: ApiKeyCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/me/keys';
};

export type CreateApiKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApiKeyError = CreateApiKeyErrors[keyof CreateApiKeyErrors];

export type CreateApiKeyResponses = {
    /**
     * Successful Response
     */
    201: ApiKeyCreated;
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type DeleteApiKeyData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Key Id
         */
        key_id: number;
    };
    query?: never;
    url: '/api/v1/me/keys/{key_id}';
};

export type DeleteApiKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiKeyError = DeleteApiKeyErrors[keyof DeleteApiKeyErrors];

export type DeleteApiKeyResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiKeyResponse = DeleteApiKeyResponses[keyof DeleteApiKeyResponses];

export type ListGithubReposData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/github/repos';
};

export type ListGithubReposErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListGithubReposError = ListGithubReposErrors[keyof ListGithubReposErrors];

export type ListGithubReposResponses = {
    /**
     * Response Listgithubrepos
     *
     * Successful Response
     */
    200: Array<RepoOption>;
};

export type ListGithubReposResponse = ListGithubReposResponses[keyof ListGithubReposResponses];

export type SearchGithubUsersData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
    };
    url: '/api/v1/github/users';
};

export type SearchGithubUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchGithubUsersError = SearchGithubUsersErrors[keyof SearchGithubUsersErrors];

export type SearchGithubUsersResponses = {
    /**
     * Response Searchgithubusers
     *
     * Successful Response
     */
    200: Array<UserOption>;
};

export type SearchGithubUsersResponse = SearchGithubUsersResponses[keyof SearchGithubUsersResponses];

export type ListCollaboratorsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/collaborators';
};

export type ListCollaboratorsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCollaboratorsError = ListCollaboratorsErrors[keyof ListCollaboratorsErrors];

export type ListCollaboratorsResponses = {
    /**
     * Response Listcollaborators
     *
     * Successful Response
     */
    200: Array<CollaboratorResponse>;
};

export type ListCollaboratorsResponse = ListCollaboratorsResponses[keyof ListCollaboratorsResponses];

export type InviteCollaboratorData = {
    body: InviteRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/invite';
};

export type InviteCollaboratorErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InviteCollaboratorError = InviteCollaboratorErrors[keyof InviteCollaboratorErrors];

export type InviteCollaboratorResponses = {
    /**
     * Successful Response
     */
    200: InviteResponse;
};

export type InviteCollaboratorResponse = InviteCollaboratorResponses[keyof InviteCollaboratorResponses];

export type ListScheduledData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/scheduled';
};

export type ListScheduledErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListScheduledError = ListScheduledErrors[keyof ListScheduledErrors];

export type ListScheduledResponses = {
    /**
     * Response Listscheduled
     *
     * Successful Response
     */
    200: Array<ScheduledOutput>;
};

export type ListScheduledResponse = ListScheduledResponses[keyof ListScheduledResponses];

export type PutScheduledData = {
    /**
     * Body
     */
    body: Array<ScheduledInput>;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/scheduled';
};

export type PutScheduledErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutScheduledError = PutScheduledErrors[keyof PutScheduledErrors];

export type PutScheduledResponses = {
    /**
     * Response Putscheduled
     *
     * Successful Response
     */
    200: Array<ScheduledOutput>;
};

export type PutScheduledResponse = PutScheduledResponses[keyof PutScheduledResponses];

export type ListDueData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: {
        /**
         * Through
         */
        through?: string | null;
    };
    url: '/api/v1/budgets/{budget}/scheduled/due';
};

export type ListDueErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDueError = ListDueErrors[keyof ListDueErrors];

export type ListDueResponses = {
    /**
     * Successful Response
     */
    200: DueList;
};

export type ListDueResponse = ListDueResponses[keyof ListDueResponses];

export type PostScheduledData = {
    body: PostRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Scheduled Id
         */
        scheduled_id: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/scheduled/{scheduled_id}/post';
};

export type PostScheduledErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostScheduledError = PostScheduledErrors[keyof PostScheduledErrors];

export type PostScheduledResponses = {
    /**
     * Successful Response
     */
    200: EntryResponse;
};

export type PostScheduledResponse = PostScheduledResponses[keyof PostScheduledResponses];

export type GetHistoryData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/budgets/{budget}/history';
};

export type GetHistoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHistoryError = GetHistoryErrors[keyof GetHistoryErrors];

export type GetHistoryResponses = {
    /**
     * Successful Response
     */
    200: HistoryPage;
};

export type GetHistoryResponse = GetHistoryResponses[keyof GetHistoryResponses];

export type GetHistoryDetailData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Sha
         */
        sha: string;
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/history/{sha}';
};

export type GetHistoryDetailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHistoryDetailError = GetHistoryDetailErrors[keyof GetHistoryDetailErrors];

export type GetHistoryDetailResponses = {
    /**
     * Successful Response
     */
    200: HistoryDetail;
};

export type GetHistoryDetailResponse = GetHistoryDetailResponses[keyof GetHistoryDetailResponses];

export type UndoChangeData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: {
        /**
         * Sha
         */
        sha?: string | null;
    };
    url: '/api/v1/budgets/{budget}/history/undo';
};

export type UndoChangeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UndoChangeError = UndoChangeErrors[keyof UndoChangeErrors];

export type UndoChangeResponses = {
    /**
     * Successful Response
     */
    200: UndoResult;
};

export type UndoChangeResponse = UndoChangeResponses[keyof UndoChangeResponses];

export type RedoChangeData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: never;
    url: '/api/v1/budgets/{budget}/history/redo';
};

export type RedoChangeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RedoChangeError = RedoChangeErrors[keyof RedoChangeErrors];

export type RedoChangeResponses = {
    /**
     * Successful Response
     */
    200: UndoResult;
};

export type RedoChangeResponse = RedoChangeResponses[keyof RedoChangeResponses];

export type NearbyPlacesData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Lat
         */
        lat: number;
        /**
         * Lon
         */
        lon: number;
    };
    url: '/api/v1/places/nearby';
};

export type NearbyPlacesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NearbyPlacesError = NearbyPlacesErrors[keyof NearbyPlacesErrors];

export type NearbyPlacesResponses = {
    /**
     * Response Nearbyplaces
     *
     * Successful Response
     */
    200: Array<NearbyPlaceResponse>;
};

export type NearbyPlacesResponse = NearbyPlacesResponses[keyof NearbyPlacesResponses];

export type SearchPlacesData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Lat
         */
        lat?: number | null;
        /**
         * Lon
         */
        lon?: number | null;
    };
    url: '/api/v1/places/search';
};

export type SearchPlacesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchPlacesError = SearchPlacesErrors[keyof SearchPlacesErrors];

export type SearchPlacesResponses = {
    /**
     * Response Searchplaces
     *
     * Successful Response
     */
    200: Array<NearbyPlaceResponse>;
};

export type SearchPlacesResponse = SearchPlacesResponses[keyof SearchPlacesResponses];

export type SuggestEntryData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Budget
         */
        budget: string;
    };
    query?: {
        /**
         * Payee
         */
        payee?: string | null;
        /**
         * Lat
         */
        lat?: number | null;
        /**
         * Lon
         */
        lon?: number | null;
        /**
         * At
         */
        at?: string | null;
    };
    url: '/api/v1/budgets/{budget}/suggest';
};

export type SuggestEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SuggestEntryError = SuggestEntryErrors[keyof SuggestEntryErrors];

export type SuggestEntryResponses = {
    /**
     * Successful Response
     */
    200: SuggestionResponse;
};

export type SuggestEntryResponse = SuggestEntryResponses[keyof SuggestEntryResponses];
