"""Generated by `money generate-cli`. Do not edit.

Every command here comes from an `x-cli` annotation on a route. To change a command, change
the annotation next to the route and regenerate.
"""

from __future__ import annotations

import json
from typing import Annotated

import typer

from money_cli.client import emit, request, resolve_budget

# Commands with no group, such as `money balance`, land here and are copied onto the root
# app by register(); Typer has no way to attach a bare command to an app it does not own.
_root = typer.Typer()


assign_app = typer.Typer(no_args_is_help=True, help="assign commands")

auth_app = typer.Typer(no_args_is_help=True, help="auth commands")

bucket_app = typer.Typer(no_args_is_help=True, help="bucket commands")

budget_app = typer.Typer(no_args_is_help=True, help="budget commands")

entry_app = typer.Typer(no_args_is_help=True, help="entry commands")

key_app = typer.Typer(no_args_is_help=True, help="key commands")

member_app = typer.Typer(no_args_is_help=True, help="member commands")

month_app = typer.Typer(no_args_is_help=True, help="month commands")

note_app = typer.Typer(no_args_is_help=True, help="note commands")

rule_app = typer.Typer(no_args_is_help=True, help="rule commands")

scheduled_app = typer.Typer(no_args_is_help=True, help="scheduled commands")



@_root.command("assign", help='Assign money to a bucket')
def assign(
    month: Annotated[str, typer.Argument(help='')],
    bucket: Annotated[str, typer.Argument(help='')],
    amount: Annotated[str, typer.Argument(help='')],
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {"bucket": bucket, "amount": amount}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "PUT",
            f"/budgets/{resolve_budget(budget)}/months/{month}/assign",
            query={},
            body=body,
        ),
        as_json=json_out,
        table='month',
    )


@_root.command("balance", help='Show who owes whom')
def balance(
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/budgets/{resolve_budget(budget)}/balances",
            query={},
            body=None,
        ),
        as_json=json_out,
        table='balances',
    )


@_root.command("history", help='Everything that has changed, newest first')
def history(
    limit: Annotated[int | None, typer.Option("--limit", help='')] = None,
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/budgets/{resolve_budget(budget)}/history",
            query={"limit": limit},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@_root.command("month", help='Envelope view for a month')
def month(
    month: Annotated[str, typer.Argument(help='')],
    person: Annotated[str | None, typer.Option("--person", "-p", help='')] = None,
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/budgets/{resolve_budget(budget)}/months/{month}",
            query={"person": person},
            body=None,
        ),
        as_json=json_out,
        table='month',
    )


@_root.command("settle", help='Record a payment between two people')
def settle(
    to: Annotated[str, typer.Argument(help='Person id being paid')],
    amount: Annotated[str, typer.Argument(help='')],
    payer: Annotated[str | None, typer.Option("--payer", help='Person id who handed over the money. Defaults to the calling user.')] = None,
    date: Annotated[str | None, typer.Option("--date", help='')] = None,
    note: Annotated[str | None, typer.Option("--note", help='')] = None,
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {"to": to, "amount": amount, "payer": payer, "date": date, "note": note}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "POST",
            f"/budgets/{resolve_budget(budget)}/settle",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


@_root.command("undo", help='Undo a change you made')
def undo(
    sha: Annotated[str | None, typer.Option("--sha", help='')] = None,
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "POST",
            f"/budgets/{resolve_budget(budget)}/history/undo",
            query={"sha": sha},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@assign_app.command("auto", help='Fund several buckets at once')
def assign_auto(
    month: Annotated[str, typer.Argument(help='')],
    strategy: Annotated[str, typer.Argument(help='How much to put in each bucket')],
    buckets: Annotated[list[str], typer.Option("--buckets", help='Limit to these buckets; all of them when omitted')] = [],
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {"strategy": strategy, "buckets": buckets}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "POST",
            f"/budgets/{resolve_budget(budget)}/months/{month}/auto-assign",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


@assign_app.command("move", help='Move money from one bucket to another')
def assign_move(
    month: Annotated[str, typer.Argument(help='')],
    source: Annotated[str, typer.Argument(help='Bucket the money leaves')],
    target: Annotated[str, typer.Argument(help='Bucket the money goes to')],
    amount: Annotated[str, typer.Argument(help='')],
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {"source": source, "target": target, "amount": amount}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "POST",
            f"/budgets/{resolve_budget(budget)}/months/{month}/move",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


@auth_app.command("whoami", help='Show the signed-in user')
def auth_whoami(
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/me",
            query={},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@bucket_app.command("list", help='Buckets for a person')
def bucket_list(
    person: Annotated[str | None, typer.Option("--person", "-p", help='')] = None,
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/budgets/{resolve_budget(budget)}/buckets",
            query={"person": person},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@bucket_app.command("set", help='Create or update one of your buckets')
def bucket_set(
    bucket_id: Annotated[str, typer.Argument(help='')],
    name: Annotated[str, typer.Argument(help='')],
    id_: Annotated[str, typer.Option("--id", help='')],
    group: Annotated[str | None, typer.Option("--group", help='')] = None,
    target: Annotated[str | None, typer.Option("--target", help='')] = None,
    archived: Annotated[bool, typer.Option("--archived", help='')] = False,
    order: Annotated[int | None, typer.Option("--order", help='Sort position within its group; ties fall back to name')] = None,
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {"name": name, "id": id_, "group": group, "target": target, "archived": archived, "order": order}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "PUT",
            f"/budgets/{resolve_budget(budget)}/buckets/{bucket_id}",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


@budget_app.command("connect", help='Connect a GitHub repo as a budget')
def budget_connect(
    slug: Annotated[str, typer.Argument(help='')],
    repo: Annotated[str, typer.Argument(help='owner/repo on GitHub')],
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {"slug": slug, "repo": repo}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "POST",
            f"/budgets",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


@budget_app.command("list", help='List budgets')
def budget_list(
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/budgets",
            query={},
            body=None,
        ),
        as_json=json_out,
        table='budgets',
    )


@entry_app.command("add", help='Record an entry')
def entry_add(
    amount: Annotated[str, typer.Argument(help='Negative for money out, positive for money in')],
    payee: Annotated[str, typer.Argument(help='')],
    date: Annotated[str | None, typer.Option("--date", "-d", help='Defaults to today')] = None,
    kind: Annotated[str | None, typer.Option("--kind", help='')] = None,
    currency: Annotated[str | None, typer.Option("--currency", help='Defaults to the budget currency')] = None,
    bucket: Annotated[str | None, typer.Option("--bucket", "-b", help='Book every share against this bucket, overriding the rule')] = None,
    note: Annotated[str | None, typer.Option("--note", "-n", help='')] = None,
    tags: Annotated[list[str], typer.Option("--tags", help='')] = [],
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {"amount": amount, "payee": payee, "date": date, "kind": kind, "currency": currency, "bucket": bucket, "note": note, "tags": tags}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "POST",
            f"/budgets/{resolve_budget(budget)}/entries",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


@entry_app.command("delete", help='Delete an entry')
def entry_delete(
    entry_id: Annotated[str, typer.Argument(help='')],
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "DELETE",
            f"/budgets/{resolve_budget(budget)}/entries/{entry_id}",
            query={},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@entry_app.command("edit", help='Edit an entry')
def entry_edit(
    entry_id: Annotated[str, typer.Argument(help='')],
    amount: Annotated[str | None, typer.Option("--amount", help='')] = None,
    payee: Annotated[str | None, typer.Option("--payee", help='')] = None,
    date: Annotated[str | None, typer.Option("--date", help='')] = None,
    note: Annotated[str | None, typer.Option("--note", help='')] = None,
    tags: Annotated[list[str], typer.Option("--tags", help='')] = [],
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {"amount": amount, "payee": payee, "date": date, "note": note, "tags": tags}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "PATCH",
            f"/budgets/{resolve_budget(budget)}/entries/{entry_id}",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


@entry_app.command("history", help='Commits that touched this entry')
def entry_history(
    entry_id: Annotated[str, typer.Argument(help='')],
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/budgets/{resolve_budget(budget)}/entries/{entry_id}/history",
            query={},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@entry_app.command("list", help='List entries')
def entry_list(
    month: Annotated[str | None, typer.Option("--month", "-m", help='')] = None,
    person: Annotated[str | None, typer.Option("--person", "-p", help='')] = None,
    bucket: Annotated[str | None, typer.Option("--bucket", "-b", help='')] = None,
    tag: Annotated[str | None, typer.Option("--tag", help='')] = None,
    payee: Annotated[str | None, typer.Option("--payee", help='')] = None,
    limit: Annotated[int | None, typer.Option("--limit", help='')] = None,
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/budgets/{resolve_budget(budget)}/entries",
            query={"month": month, "person": person, "bucket": bucket, "tag": tag, "payee": payee, "limit": limit},
            body=None,
        ),
        as_json=json_out,
        table='entries',
    )


@entry_app.command("payees", help='Payees you have used before')
def entry_payees(
    q: Annotated[str | None, typer.Option("--q", help='')] = None,
    limit: Annotated[int | None, typer.Option("--limit", help='')] = None,
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/budgets/{resolve_budget(budget)}/entries/payees",
            query={"q": q, "limit": limit},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@entry_app.command("preview", help='Show how an entry would be split, without saving it')
def entry_preview(
    amount: Annotated[str, typer.Argument(help='Negative for money out, positive for money in')],
    payee: Annotated[str, typer.Argument(help='')],
    date: Annotated[str | None, typer.Option("--date", help='Defaults to today')] = None,
    kind: Annotated[str | None, typer.Option("--kind", help='')] = None,
    currency: Annotated[str | None, typer.Option("--currency", help='Defaults to the budget currency')] = None,
    bucket: Annotated[str | None, typer.Option("--bucket", help='Book every share against this bucket, overriding the rule')] = None,
    note: Annotated[str | None, typer.Option("--note", help='')] = None,
    tags: Annotated[list[str], typer.Option("--tags", help='')] = [],
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {"amount": amount, "payee": payee, "date": date, "kind": kind, "currency": currency, "bucket": bucket, "note": note, "tags": tags}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "POST",
            f"/budgets/{resolve_budget(budget)}/entries/preview",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


@entry_app.command("suggest", help='A guessed entry, with its reasoning')
def entry_suggest(
    payee: Annotated[str | None, typer.Option("--payee", help='')] = None,
    lat: Annotated[str | None, typer.Option("--lat", help='')] = None,
    lon: Annotated[str | None, typer.Option("--lon", help='')] = None,
    at: Annotated[str | None, typer.Option("--at", help='')] = None,
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/budgets/{resolve_budget(budget)}/suggest",
            query={"payee": payee, "lat": lat, "lon": lon, "at": at},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@key_app.command("create", help='Create an API key')
def key_create(
    name: Annotated[str, typer.Argument(help='')],
    scopes: Annotated[list[str], typer.Option("--scopes", help='')] = [],
    expires_in_days: Annotated[int | None, typer.Option("--expires-in-days", help='')] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {"name": name, "scopes": scopes, "expires_in_days": expires_in_days}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "POST",
            f"/me/keys",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


@key_app.command("delete", help='Revoke an API key')
def key_delete(
    key_id: Annotated[int, typer.Argument(help='')],
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "DELETE",
            f"/me/keys/{key_id}",
            query={},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@key_app.command("list", help='Your API keys')
def key_list(
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/me/keys",
            query={},
            body=None,
        ),
        as_json=json_out,
        table='keys',
    )


@member_app.command("invite", help="Invite someone to the budget's data repo")
def member_invite(
    login: Annotated[str, typer.Argument(help='GitHub login')],
    name: Annotated[str | None, typer.Option("--name", help='Display name; defaults to the login')] = None,
    person: Annotated[str | None, typer.Option("--person", help='Person id; derived from the login')] = None,
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {"login": login, "name": name, "person": person}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "POST",
            f"/budgets/{resolve_budget(budget)}/invite",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


@member_app.command("list", help='Who is in this budget')
def member_list(
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/budgets/{resolve_budget(budget)}/members",
            query={},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@member_app.command("set", help='Replace the member list')
def member_set(
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "PUT",
            f"/budgets/{resolve_budget(budget)}/members",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


@month_app.command("close", help='Tag this month as closed')
def month_close(
    month: Annotated[str, typer.Argument(help='')],
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "POST",
            f"/budgets/{resolve_budget(budget)}/months/{month}/close",
            query={},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@month_app.command("reopen", help='Remove the close tag')
def month_reopen(
    month: Annotated[str, typer.Argument(help='')],
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "DELETE",
            f"/budgets/{resolve_budget(budget)}/months/{month}/close",
            query={},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@note_app.command("set", help='Write the long-form note for an entry')
def note_set(
    entry_id: Annotated[str, typer.Argument(help='')],
    text: Annotated[str, typer.Argument(help='Markdown. Empty removes the note.')],
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {"text": text}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "PUT",
            f"/budgets/{resolve_budget(budget)}/entries/{entry_id}/note",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


@note_app.command("show", help='Long-form note for an entry')
def note_show(
    entry_id: Annotated[str, typer.Argument(help='')],
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/budgets/{resolve_budget(budget)}/entries/{entry_id}/note",
            query={},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@rule_app.command("list", help='Default split rules, in match order')
def rule_list(
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/budgets/{resolve_budget(budget)}/rules",
            query={},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@rule_app.command("set", help='Replace the whole rule list')
def rule_set(
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "PUT",
            f"/budgets/{resolve_budget(budget)}/rules",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


@scheduled_app.command("due", help='Recurring entries that are due')
def scheduled_due(
    through: Annotated[str | None, typer.Option("--through", help='')] = None,
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/budgets/{resolve_budget(budget)}/scheduled/due",
            query={"through": through},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@scheduled_app.command("list", help='Recurring entries')
def scheduled_list(
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    emit(
        request(
            "GET",
            f"/budgets/{resolve_budget(budget)}/scheduled",
            query={},
            body=None,
        ),
        as_json=json_out,
        table=None,
    )


@scheduled_app.command("post", help='Turn a due recurrence into a real entry')
def scheduled_post(
    scheduled_id: Annotated[str, typer.Argument(help='')],
    date: Annotated[str, typer.Argument(help='Defaults to today')],
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {"date": date}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "POST",
            f"/budgets/{resolve_budget(budget)}/scheduled/{scheduled_id}/post",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


@scheduled_app.command("set", help='Replace the recurring entries')
def scheduled_set(
    budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None,
    raw: Annotated[str | None, typer.Option("--raw", help="JSON merged into the body, for fields with no flag")] = None,
    json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False,
) -> None:
    body = {}
    if raw:
        body.update(json.loads(raw))
    emit(
        request(
            "PUT",
            f"/budgets/{resolve_budget(budget)}/scheduled",
            query={},
            body=body,
        ),
        as_json=json_out,
        table=None,
    )


def register(app: typer.Typer) -> None:
    """Attach every generated command to the root app."""
    app.registered_commands.extend(_root.registered_commands)
    app.add_typer(assign_app, name="assign")
    app.add_typer(auth_app, name="auth")
    app.add_typer(bucket_app, name="bucket")
    app.add_typer(budget_app, name="budget")
    app.add_typer(entry_app, name="entry")
    app.add_typer(key_app, name="key")
    app.add_typer(member_app, name="member")
    app.add_typer(month_app, name="month")
    app.add_typer(note_app, name="note")
    app.add_typer(rule_app, name="rule")
    app.add_typer(scheduled_app, name="scheduled")
