"""Generate CLI commands from the API's OpenAPI schema.

A route opts in by carrying `x-cli`; see specs/cli.md. The output is checked in, so the CLI
starts without parsing a schema or reaching the network, and CI fails if regenerating
produces a diff.
"""

from __future__ import annotations

import json
import keyword
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

HEADER = '''\
"""Generated by `money generate-cli`. Do not edit.

Every command here comes from an `x-cli` annotation on a route. To change a command, change
the annotation next to the route and regenerate.
"""

from __future__ import annotations

import json
from typing import Annotated

import typer

from money_cli.client import emit, request, resolve_budget

# Commands with no group, such as `money balance`, land here and are copied onto the root
# app by register(); Typer has no way to attach a bare command to an app it does not own.
_root = typer.Typer()

'''

# Which renderer `emit` should use for an operation's result. Anything unlisted prints JSON.
TABLES = {
    "listEntries": "entries",
    "getBalances": "balances",
    "getMonth": "month",
    "assignToBucket": "month",
    "listBudgets": "budgets",
    "listApiKeys": "keys",
}

SCALARS = {"string": "str", "integer": "int", "boolean": "bool", "number": "str"}


@dataclass
class Param:
    """One CLI parameter, sourced from a path, query, or body field."""

    name: str
    py_name: str
    python_type: str
    source: str  # "path" | "query" | "body"
    required: bool
    help: str = ""
    alias: str | None = None
    positional: bool = False

    def declaration(self) -> str:
        if self.positional:
            annotation = f"Annotated[{self.python_type}, typer.Argument(help={self.help!r})]"
            return f"{self.py_name}: {annotation}"

        flags = [f'"--{self.name.replace("_", "-")}"']
        if self.alias:
            flags.append(f'"{self.alias}"')
        option = f"typer.Option({', '.join(flags)}, help={self.help!r})"

        if self.required:
            return f"{self.py_name}: Annotated[{self.python_type}, {option}]"
        default = "None" if not self.python_type.startswith(("bool", "list")) else _empty(self)
        optional = (
            self.python_type
            if self.python_type.startswith(("bool", "list"))
            else f"{self.python_type} | None"
        )
        return f"{self.py_name}: Annotated[{optional}, {option}] = {default}"


def _empty(param: Param) -> str:
    return "False" if param.python_type == "bool" else "[]"


@dataclass
class Command:
    group: str | None
    name: str
    func_name: str
    method: str
    path: str
    summary: str
    params: list[Param] = field(default_factory=list)
    has_body: bool = False
    table: str | None = None


def python_type_for(schema: dict[str, Any]) -> str | None:
    """Map a JSON-schema node onto a CLI-expressible Python type.

    Returns None for anything a flag cannot express — nested objects, lists of objects. Those
    fields stay reachable through `--raw` and `money api`, rather than being flattened into a
    flag syntax nobody would remember.
    """
    for option in schema.get("anyOf", [schema]):
        if option.get("type") == "null":
            continue
        kind = option.get("type")
        if kind in SCALARS:
            return SCALARS[kind]
        if kind == "array" and option.get("items", {}).get("type") == "string":
            return "list[str]"
        if "$ref" in option:
            return "str"  # enums arrive as $ref and are plain strings on the wire
    return None


def sanitize(name: str) -> str:
    return f"{name}_" if keyword.iskeyword(name) or name in {"json", "id"} else name


def collect(spec: dict[str, Any], path: str, method: str, operation: dict[str, Any]) -> Command:
    cli = operation["x-cli"]
    words = cli["command"].split()
    group = words[0] if len(words) > 1 else None
    name = words[-1]

    positional = list(cli.get("args", []))
    aliases: dict[str, str] = cli.get("aliases", {})
    params: list[Param] = []
    seen: set[str] = set()

    def add(name_: str, schema: dict[str, Any], source: str, required: bool, help_: str) -> None:
        if name_ in seen or name_ == "budget":
            return  # budget is resolved from config, never a generated flag
        python_type = python_type_for(schema)
        if python_type is None:
            return
        seen.add(name_)
        params.append(
            Param(
                name=name_,
                py_name=sanitize(name_),
                python_type=python_type,
                source=source,
                required=required or name_ in positional,
                help=help_,
                alias=aliases.get(name_),
                positional=name_ in positional,
            )
        )

    for parameter in operation.get("parameters", []):
        if parameter["in"] not in ("path", "query"):
            # Header and cookie params come from the auth dependency, not from the user.
            continue
        add(
            parameter["name"],
            parameter.get("schema", {}),
            parameter["in"],
            parameter.get("required", False),
            parameter.get("description", ""),
        )

    body_schema = _body_schema(spec, operation)
    for prop_name, prop in (body_schema.get("properties") or {}).items():
        add(
            prop_name,
            prop,
            "body",
            prop_name in body_schema.get("required", []),
            prop.get("description", ""),
        )

    def order(param: Param) -> tuple[int, int]:
        # Python forbids a parameter without a default after one with a default, so required
        # options must precede optional ones.
        if param.positional:
            return (0, positional.index(param.name))
        return (1 if param.required else 2, 0)

    params.sort(key=order)

    return Command(
        group=group,
        name=name,
        func_name="_".join(words).replace("-", "_"),
        method=method.upper(),
        path=path,
        summary=cli.get("summary") or operation.get("summary", ""),
        params=params,
        has_body=bool(body_schema),
        table=TABLES.get(operation.get("operationId", "")),
    )


def _body_schema(spec: dict[str, Any], operation: dict[str, Any]) -> dict[str, Any]:
    content = (operation.get("requestBody") or {}).get("content", {})
    schema = content.get("application/json", {}).get("schema")
    if not schema:
        return {}
    if "$ref" in schema:
        ref = schema["$ref"].rsplit("/", 1)[-1]
        return spec["components"]["schemas"].get(ref, {})
    return schema


def render(command: Command, prefix: str) -> str:
    decorator_target = f"{command.group}_app" if command.group else "_root"
    declarations = [param.declaration() for param in command.params]

    # Every command takes --budget when its path needs one, plus --json for raw output.
    if "{budget}" in command.path:
        declarations.append(
            'budget: Annotated[str | None, typer.Option("--budget", help="Budget slug")] = None'
        )
    if command.has_body:
        declarations.append(
            'raw: Annotated[str | None, typer.Option("--raw", '
            'help="JSON merged into the body, for fields with no flag")] = None'
        )
    declarations.append(
        'json_out: Annotated[bool, typer.Option("--json", help="Print raw JSON")] = False'
    )

    query = {p.name: p.py_name for p in command.params if p.source == "query"}
    body = {p.name: p.py_name for p in command.params if p.source == "body"}
    path_expr = command.path.removeprefix(prefix)
    if "{budget}" in path_expr:
        path_expr = path_expr.replace("{budget}", "{resolve_budget(budget)}")
    for param in command.params:
        if param.source == "path":
            path_expr = path_expr.replace(f"{{{param.name}}}", f"{{{param.py_name}}}")

    lines = [
        f'@{decorator_target}.command("{command.name}", help={command.summary!r})',
        f"def {command.func_name}(",
        *[f"    {declaration}," for declaration in declarations],
        ") -> None:",
    ]
    if command.has_body:
        lines += [
            f"    body = {_dict_literal(body)}",
            "    if raw:",
            "        body.update(json.loads(raw))",
        ]
    lines += [
        "    emit(",
        "        request(",
        f'            "{command.method}",',
        f'            f"{path_expr}",',
        f"            query={_dict_literal(query)},",
        f"            body={'body' if command.has_body else 'None'},",
        "        ),",
        "        as_json=json_out,",
        f"        table={command.table!r},",
        "    )",
        "",
        "",
    ]
    return "\n".join(lines)


def _dict_literal(mapping: dict[str, str]) -> str:
    if not mapping:
        return "{}"
    items = ", ".join(f'"{key}": {value}' for key, value in mapping.items())
    return "{" + items + "}"


def generate(spec: dict[str, Any], prefix: str = "/api/v1") -> str:
    commands = [
        collect(spec, path, method, operation)
        for path, methods in spec["paths"].items()
        for method, operation in methods.items()
        if isinstance(operation, dict) and "x-cli" in operation
    ]
    commands.sort(key=lambda c: (c.group or "", c.name))

    groups = sorted({c.group for c in commands if c.group})
    out = [HEADER]
    for group in groups:
        out.append(f'{group}_app = typer.Typer(no_args_is_help=True, help="{group} commands")\n')
    out.append("\n")

    for command in commands:
        out.append(render(command, prefix))

    out.append("def register(app: typer.Typer) -> None:")
    out.append('    """Attach every generated command to the root app."""')
    out.append("    app.registered_commands.extend(_root.registered_commands)")
    for group in groups:
        out.append(f'    app.add_typer({group}_app, name="{group}")')
    out.append("")

    return "\n".join(out)


def write(spec: dict[str, Any], destination: Path) -> None:
    destination.write_text(generate(spec), encoding="utf-8")


def load_spec(source: str) -> dict[str, Any]:
    """Read the schema from a file, a URL, or the local app."""
    if source.startswith(("http://", "https://")):
        import httpx

        return httpx.get(source, timeout=30.0).json()
    if source == "app":
        from money.api.app import create_app

        return create_app().openapi()
    return json.loads(Path(source).read_text(encoding="utf-8"))
