// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { acceptHandoff, assignToBucket, connectBudget, createApiKey, createEntry, deleteApiKey, deleteEntry, finishGithubLogin, getAuthConfig, getBalances, getBudget, getEntry, getEntryHistory, getMe, getMonth, listApiKeys, listBuckets, listBudgets, listEntries, listMembers, listRules, logout, type Options, pollDeviceLogin, previewSplit, putBucket, putMembers, putRules, settleUp, startDeviceLogin, startGithubLogin, updateEntry } from '../sdk.gen';
import type { AcceptHandoffData, AcceptHandoffError, AssignToBucketData, AssignToBucketError, AssignToBucketResponse, ConnectBudgetData, ConnectBudgetError, ConnectBudgetResponse, CreateApiKeyData, CreateApiKeyError, CreateApiKeyResponse, CreateEntryData, CreateEntryError, CreateEntryResponse, DeleteApiKeyData, DeleteApiKeyError, DeleteApiKeyResponse, DeleteEntryData, DeleteEntryError, DeleteEntryResponse, FinishGithubLoginData, FinishGithubLoginError, GetAuthConfigData, GetAuthConfigResponse, GetBalancesData, GetBalancesError, GetBalancesResponse, GetBudgetData, GetBudgetError, GetBudgetResponse, GetEntryData, GetEntryError, GetEntryHistoryData, GetEntryHistoryError, GetEntryHistoryResponse, GetEntryResponse, GetMeData, GetMeError, GetMeResponse, GetMonthData, GetMonthError, GetMonthResponse, ListApiKeysData, ListApiKeysError, ListApiKeysResponse, ListBucketsData, ListBucketsError, ListBucketsResponse, ListBudgetsData, ListBudgetsError, ListBudgetsResponse, ListEntriesData, ListEntriesError, ListEntriesResponse, ListMembersData, ListMembersError, ListMembersResponse, ListRulesData, ListRulesError, ListRulesResponse, LogoutData, LogoutResponse, PollDeviceLoginData, PollDeviceLoginError, PollDeviceLoginResponse, PreviewSplitData, PreviewSplitError, PreviewSplitResponse, PutBucketData, PutBucketError, PutBucketResponse, PutMembersData, PutMembersError, PutMembersResponse, PutRulesData, PutRulesError, PutRulesResponse, SettleUpData, SettleUpError, SettleUpResponse, StartDeviceLoginData, StartDeviceLoginResponse, StartGithubLoginData, StartGithubLoginError, UpdateEntryData, UpdateEntryError, UpdateEntryResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAuthConfigQueryKey = (options?: Options<GetAuthConfigData>) => createQueryKey('getAuthConfig', options);

/**
 * Get Auth Config
 *
 * Where this deployment's sign-in starts.
 *
 * Computed server-side because only the server knows whether it is production or a preview;
 * the browser guessing its own prod origin from the hostname would be one more thing to
 * keep correct.
 */
export const getAuthConfigOptions = (options?: Options<GetAuthConfigData>) => queryOptions<GetAuthConfigResponse, DefaultError, GetAuthConfigResponse, ReturnType<typeof getAuthConfigQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAuthConfig({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAuthConfigQueryKey(options)
});

export const startGithubLoginQueryKey = (options?: Options<StartGithubLoginData>) => createQueryKey('startGithubLogin', options);

/**
 * Begin browser sign-in
 */
export const startGithubLoginOptions = (options?: Options<StartGithubLoginData>) => queryOptions<unknown, StartGithubLoginError, unknown, ReturnType<typeof startGithubLoginQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await startGithubLogin({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: startGithubLoginQueryKey(options)
});

export const finishGithubLoginQueryKey = (options: Options<FinishGithubLoginData>) => createQueryKey('finishGithubLogin', options);

/**
 * OAuth callback
 */
export const finishGithubLoginOptions = (options: Options<FinishGithubLoginData>) => queryOptions<unknown, FinishGithubLoginError, unknown, ReturnType<typeof finishGithubLoginQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await finishGithubLogin({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: finishGithubLoginQueryKey(options)
});

export const acceptHandoffQueryKey = (options: Options<AcceptHandoffData>) => createQueryKey('acceptHandoff', options);

/**
 * Accept a preview sign-in ticket
 *
 * Complete a sign-in that production started on this preview's behalf.
 *
 * The ticket is checked against *this* deployment's own hostname, so a ticket minted for
 * `pr-42` is useless at `pr-43` even though both trust the same signing key.
 */
export const acceptHandoffOptions = (options: Options<AcceptHandoffData>) => queryOptions<unknown, AcceptHandoffError, unknown, ReturnType<typeof acceptHandoffQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await acceptHandoff({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: acceptHandoffQueryKey(options)
});

/**
 * Sign out
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Begin CLI sign-in
 */
export const startDeviceLoginMutation = (options?: Partial<Options<StartDeviceLoginData>>): UseMutationOptions<StartDeviceLoginResponse, DefaultError, Options<StartDeviceLoginData>> => {
    const mutationOptions: UseMutationOptions<StartDeviceLoginResponse, DefaultError, Options<StartDeviceLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await startDeviceLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Exchange an approved device code for an API key
 *
 * Returns `pending` until the user approves in their browser.
 *
 * On approval this mints a *money* API key rather than handing the CLI the GitHub token,
 * so revoking CLI access never means revoking GitHub access.
 */
export const pollDeviceLoginMutation = (options?: Partial<Options<PollDeviceLoginData>>): UseMutationOptions<PollDeviceLoginResponse, PollDeviceLoginError, Options<PollDeviceLoginData>> => {
    const mutationOptions: UseMutationOptions<PollDeviceLoginResponse, PollDeviceLoginError, Options<PollDeviceLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await pollDeviceLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listBudgetsQueryKey = (options?: Options<ListBudgetsData>) => createQueryKey('listBudgets', options);

/**
 * Budgets you can see
 *
 * Every linked budget whose repo GitHub says the caller can read.
 *
 * Budgets they cannot read are omitted, not reported as forbidden.
 */
export const listBudgetsOptions = (options?: Options<ListBudgetsData>) => queryOptions<ListBudgetsResponse, ListBudgetsError, ListBudgetsResponse, ReturnType<typeof listBudgetsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBudgets({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBudgetsQueryKey(options)
});

/**
 * Connect a GitHub repo as a budget
 */
export const connectBudgetMutation = (options?: Partial<Options<ConnectBudgetData>>): UseMutationOptions<ConnectBudgetResponse, ConnectBudgetError, Options<ConnectBudgetData>> => {
    const mutationOptions: UseMutationOptions<ConnectBudgetResponse, ConnectBudgetError, Options<ConnectBudgetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await connectBudget({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getBudgetQueryKey = (options: Options<GetBudgetData>) => createQueryKey('getBudget', options);

/**
 * One budget
 */
export const getBudgetOptions = (options: Options<GetBudgetData>) => queryOptions<GetBudgetResponse, GetBudgetError, GetBudgetResponse, ReturnType<typeof getBudgetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBudget({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBudgetQueryKey(options)
});

export const listMembersQueryKey = (options: Options<ListMembersData>) => createQueryKey('listMembers', options);

/**
 * Who is in this budget
 */
export const listMembersOptions = (options: Options<ListMembersData>) => queryOptions<ListMembersResponse, ListMembersError, ListMembersResponse, ReturnType<typeof listMembersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listMembers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listMembersQueryKey(options)
});

/**
 * Replace the member list
 *
 * Replaces the list wholesale, so removals are expressible and not just additions.
 *
 * Membership decides who can be assigned a share, not who can reach the budget — that is
 * GitHub repo access. Someone listed here without repo access simply never signs in.
 */
export const putMembersMutation = (options?: Partial<Options<PutMembersData>>): UseMutationOptions<PutMembersResponse, PutMembersError, Options<PutMembersData>> => {
    const mutationOptions: UseMutationOptions<PutMembersResponse, PutMembersError, Options<PutMembersData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putMembers({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getMonthQueryKey = (options: Options<GetMonthData>) => createQueryKey('getMonth', options);

/**
 * Envelope view for a month
 *
 * Defaults to the calling user's own envelopes, since buckets are per person.
 */
export const getMonthOptions = (options: Options<GetMonthData>) => queryOptions<GetMonthResponse, GetMonthError, GetMonthResponse, ReturnType<typeof getMonthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMonth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMonthQueryKey(options)
});

/**
 * Assign money to a bucket
 */
export const assignToBucketMutation = (options?: Partial<Options<AssignToBucketData>>): UseMutationOptions<AssignToBucketResponse, AssignToBucketError, Options<AssignToBucketData>> => {
    const mutationOptions: UseMutationOptions<AssignToBucketResponse, AssignToBucketError, Options<AssignToBucketData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await assignToBucket({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create or update one of your buckets
 */
export const putBucketMutation = (options?: Partial<Options<PutBucketData>>): UseMutationOptions<PutBucketResponse, PutBucketError, Options<PutBucketData>> => {
    const mutationOptions: UseMutationOptions<PutBucketResponse, PutBucketError, Options<PutBucketData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putBucket({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listBucketsQueryKey = (options: Options<ListBucketsData>) => createQueryKey('listBuckets', options);

/**
 * Buckets for a person
 */
export const listBucketsOptions = (options: Options<ListBucketsData>) => queryOptions<ListBucketsResponse, ListBucketsError, ListBucketsResponse, ReturnType<typeof listBucketsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBuckets({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBucketsQueryKey(options)
});

export const getBalancesQueryKey = (options: Options<GetBalancesData>) => createQueryKey('getBalances', options);

/**
 * Who owes whom
 */
export const getBalancesOptions = (options: Options<GetBalancesData>) => queryOptions<GetBalancesResponse, GetBalancesError, GetBalancesResponse, ReturnType<typeof getBalancesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBalances({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBalancesQueryKey(options)
});

/**
 * Record a payment between two people
 *
 * A settlement moves both net positions and touches no envelope.
 */
export const settleUpMutation = (options?: Partial<Options<SettleUpData>>): UseMutationOptions<SettleUpResponse, SettleUpError, Options<SettleUpData>> => {
    const mutationOptions: UseMutationOptions<SettleUpResponse, SettleUpError, Options<SettleUpData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await settleUp({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listEntriesQueryKey = (options: Options<ListEntriesData>) => createQueryKey('listEntries', options);

/**
 * List entries
 */
export const listEntriesOptions = (options: Options<ListEntriesData>) => queryOptions<ListEntriesResponse, ListEntriesError, ListEntriesResponse, ReturnType<typeof listEntriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listEntries({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listEntriesQueryKey(options)
});

/**
 * Record an entry
 */
export const createEntryMutation = (options?: Partial<Options<CreateEntryData>>): UseMutationOptions<CreateEntryResponse, CreateEntryError, Options<CreateEntryData>> => {
    const mutationOptions: UseMutationOptions<CreateEntryResponse, CreateEntryError, Options<CreateEntryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createEntry({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete an entry
 */
export const deleteEntryMutation = (options?: Partial<Options<DeleteEntryData>>): UseMutationOptions<DeleteEntryResponse, DeleteEntryError, Options<DeleteEntryData>> => {
    const mutationOptions: UseMutationOptions<DeleteEntryResponse, DeleteEntryError, Options<DeleteEntryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteEntry({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEntryQueryKey = (options: Options<GetEntryData>) => createQueryKey('getEntry', options);

/**
 * Get one entry
 */
export const getEntryOptions = (options: Options<GetEntryData>) => queryOptions<GetEntryResponse, GetEntryError, GetEntryResponse, ReturnType<typeof getEntryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEntry({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEntryQueryKey(options)
});

/**
 * Edit an entry
 */
export const updateEntryMutation = (options?: Partial<Options<UpdateEntryData>>): UseMutationOptions<UpdateEntryResponse, UpdateEntryError, Options<UpdateEntryData>> => {
    const mutationOptions: UseMutationOptions<UpdateEntryResponse, UpdateEntryError, Options<UpdateEntryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateEntry({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEntryHistoryQueryKey = (options: Options<GetEntryHistoryData>) => createQueryKey('getEntryHistory', options);

/**
 * Commits that touched this entry
 */
export const getEntryHistoryOptions = (options: Options<GetEntryHistoryData>) => queryOptions<GetEntryHistoryResponse, GetEntryHistoryError, GetEntryHistoryResponse, ReturnType<typeof getEntryHistoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEntryHistory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEntryHistoryQueryKey(options)
});

/**
 * Show how an entry would be split, without saving it
 *
 * Answers "what will this rule do?" before anything is committed.
 */
export const previewSplitMutation = (options?: Partial<Options<PreviewSplitData>>): UseMutationOptions<PreviewSplitResponse, PreviewSplitError, Options<PreviewSplitData>> => {
    const mutationOptions: UseMutationOptions<PreviewSplitResponse, PreviewSplitError, Options<PreviewSplitData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await previewSplit({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listRulesQueryKey = (options: Options<ListRulesData>) => createQueryKey('listRules', options);

/**
 * Default split rules, in match order
 */
export const listRulesOptions = (options: Options<ListRulesData>) => queryOptions<ListRulesResponse, ListRulesError, ListRulesResponse, ReturnType<typeof listRulesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRules({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRulesQueryKey(options)
});

/**
 * Replace the whole rule list
 *
 * Replaces the list wholesale, because order is meaningful: first match wins.
 *
 * Editing one rule in place would leave the caller unable to express a reordering.
 */
export const putRulesMutation = (options?: Partial<Options<PutRulesData>>): UseMutationOptions<PutRulesResponse, PutRulesError, Options<PutRulesData>> => {
    const mutationOptions: UseMutationOptions<PutRulesResponse, PutRulesError, Options<PutRulesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putRules({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getMeQueryKey = (options?: Options<GetMeData>) => createQueryKey('getMe', options);

/**
 * Who am I
 */
export const getMeOptions = (options?: Options<GetMeData>) => queryOptions<GetMeResponse, GetMeError, GetMeResponse, ReturnType<typeof getMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMeQueryKey(options)
});

export const listApiKeysQueryKey = (options?: Options<ListApiKeysData>) => createQueryKey('listApiKeys', options);

/**
 * Your API keys
 */
export const listApiKeysOptions = (options?: Options<ListApiKeysData>) => queryOptions<ListApiKeysResponse, ListApiKeysError, ListApiKeysResponse, ReturnType<typeof listApiKeysQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listApiKeys({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listApiKeysQueryKey(options)
});

/**
 * Create an API key
 *
 * The token is returned once here and never again; only its hash is stored.
 */
export const createApiKeyMutation = (options?: Partial<Options<CreateApiKeyData>>): UseMutationOptions<CreateApiKeyResponse, CreateApiKeyError, Options<CreateApiKeyData>> => {
    const mutationOptions: UseMutationOptions<CreateApiKeyResponse, CreateApiKeyError, Options<CreateApiKeyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createApiKey({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Revoke an API key
 */
export const deleteApiKeyMutation = (options?: Partial<Options<DeleteApiKeyData>>): UseMutationOptions<DeleteApiKeyResponse, DeleteApiKeyError, Options<DeleteApiKeyData>> => {
    const mutationOptions: UseMutationOptions<DeleteApiKeyResponse, DeleteApiKeyError, Options<DeleteApiKeyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiKey({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
